[package]
name = "xtask"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
anyhow = "1"
pulldown-cmark = "0.12"
serde_yaml = "0.9"
toml_edit = "0.22"

[dev-dependencies]
tempfile = "3"

[lib]
path = "src/lib.rs"

[[bin]]
name = "xtask"
path = "src/main.rs"
