#!/usr/bin/env python3
"""Exercise the maintained admission entry point in isolated Git candidates."""

from __future__ import annotations

import json
import importlib.util
import hashlib
import os
from pathlib import Path
import shutil
import stat
import subprocess
import tempfile
from typing import Any, Sequence


HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[3]
RUNNER = ROOT / "rebuild/scripts/validate"
EVIDENCE_ARCHIVE = HERE / "evidence_archive.py"
EVIDENCE_ARCHIVE_VERIFIER = ROOT / "rebuild/scripts/verify-validation-archive"
GATE = HERE / "gate.py"
RESOURCE_ESTIMATE = HERE / "resource-estimate.json"
HARNESS = HERE / "harness.py"
AUTHORIZATION_ASSERTION = "v11-openai-codex-project-health-three-targets"
PROVIDER_AUTHORIZATION_ASSERTION = "openai-codex-background-semantic-bounded-rust-v1"


def write_executable(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    path.chmod(path.stat().st_mode | stat.S_IXUSR)


def run(argv: Sequence[str], *, cwd: Path, env: dict[str, str] | None = None) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        list(argv), cwd=cwd, env=env, text=True, capture_output=True, check=False
    )


def git(candidate: Path, *arguments: str) -> subprocess.CompletedProcess[str]:
    return run(("git", *arguments), cwd=candidate)


def structured_stdout(result: subprocess.CompletedProcess[str]) -> dict[str, Any]:
    try:
        value = json.loads(result.stdout)
    except json.JSONDecodeError as error:
        raise AssertionError(f"entry point did not emit JSON: {result.stdout!r}") from error
    assert isinstance(value, dict)
    return value


def bytecode_artifacts(candidate: Path) -> list[str]:
    artifacts = []
    for path in candidate.rglob("*"):
        if path.name == "__pycache__" or path.suffix in {".pyc", ".pyo"}:
            artifacts.append(path.relative_to(candidate).as_posix())
    return sorted(artifacts)


def make_candidate(parent: Path) -> tuple[Path, dict[str, str], Path, Path]:
    candidate = parent / "candidate"
    runner = candidate / "rebuild/scripts/validate"
    evidence_archive = candidate / "rebuild/validation/end-to-end/multi-repository/evidence_archive.py"
    evidence_archive_verifier = candidate / "rebuild/scripts/verify-validation-archive"
    gate = candidate / "rebuild/validation/end-to-end/multi-repository/gate.py"
    resource_estimate = candidate / "rebuild/validation/end-to-end/multi-repository/resource-estimate.json"
    runner.parent.mkdir(parents=True)
    gate.parent.mkdir(parents=True)
    shutil.copy2(RUNNER, runner)
    shutil.copy2(EVIDENCE_ARCHIVE, evidence_archive)
    shutil.copy2(EVIDENCE_ARCHIVE_VERIFIER, evidence_archive_verifier)
    shutil.copy2(GATE, gate)
    for name in ("performance.py", "performance-budgets.json", "final_evidence.py"):
        shutil.copy2(GATE.with_name(name), gate.with_name(name))
    shutil.copy2(RESOURCE_ESTIMATE, resource_estimate)
    shutil.copy2(GATE.with_name("result_contract.py"), gate.with_name("result_contract.py"))

    (candidate / ".gitignore").write_text("/rebuild/.local/\n", encoding="utf-8")
    manifest = candidate / "rebuild/validation/shared/fixture-manifest.json"
    manifest.parent.mkdir(parents=True)
    manifest.write_text(json.dumps({
        "schema_version": 1,
        "fixtures": [
            {"id": "v01-python", "validation_id": "V01", "content_sha256": "a" * 64},
            {"id": "v11-polyglot-medium", "validation_id": "V11", "content_sha256": "b" * 64},
            {"id": "repository-intelligence-realistic-v1", "validation_id": "RI-REALISTIC", "content_sha256": "f" * 64},
            {"id": "v12-current-codex-mcp-completion", "validation_id": "V12", "content_sha256": "1" * 64},
            {"id": "v07-background-provider-bounded-rust", "validation_id": "V07", "content_sha256": "2" * 64},
        ],
    }), encoding="utf-8")
    (candidate / "rebuild/Cargo.toml").write_text(
        "[workspace]\nresolver = \"2\"\nmembers = []\n", encoding="utf-8"
    )
    (candidate / "rebuild/Cargo.lock").write_text(
        "# synthetic gate-entrypoint fixture\nversion = 4\n", encoding="utf-8"
    )
    (candidate / "rebuild/validation/shared/contract-coverage.json").write_text(
        "{}\n", encoding="utf-8"
    )
    mcp_test = candidate / "rebuild/crates/volicord-host/tests/mcp.rs"
    mcp_test.parent.mkdir(parents=True, exist_ok=True)
    mcp_test.write_text("// synthetic tracked owner\n", encoding="utf-8")

    write_executable(candidate / "rebuild/install.sh", "#!/bin/sh\nexit 0\n")
    write_executable(
        candidate / "rebuild/scripts/check-fixture-manifest",
        "#!/bin/sh\n"
        "if [ \"${VALIDATION_DIRTY_PROBE:-0}\" = 1 ]; then\n"
        "  printf 'generated by admission probe\\n' > admission-generated-dirty.txt\n"
        "fi\n"
        "exit 0\n",
    )
    for relative in (
        "rebuild/validation/end-to-end/multi-repository/gate_self_test.py",
        "rebuild/validation/end-to-end/multi-repository/gate_entrypoint_self_test.py",
        "rebuild/validation/end-to-end/multi-repository/evidence_archive_self_test.py",
        "rebuild/scripts/check-validation-report",
        "rebuild/validation/shared/contract_coverage.py",
        "rebuild/scripts/check-architecture-contracts",
        "rebuild/validation/repository-intelligence/realistic-qualification/assertions.py",
        "rebuild/validation/dogfood/harness.py",
        "rebuild/validation/dogfood/qualification_policy.py",
        "rebuild/validation/dogfood/qualification_self_test.py",
        "rebuild/validation/dogfood/assertions.py",
        "rebuild/validation/dogfood/campaign_self_test.py",
        "rebuild/validation/dogfood/remediation_integration.py",
        "rebuild/validation/privacy/background-provider-qualification/harness.py",
    ):
        write_executable(
            candidate / relative,
            "#!/usr/bin/env python3\nraise SystemExit(0)\n",
        )
    write_executable(
        candidate / "rebuild/validation/dogfood/assertions.py",
        "#!/usr/bin/env python3\n"
        "import os, sys\n"
        "if os.environ.get('DOGFOOD_ASSERTIONS_FAIL') == '1':\n"
        "    print('controlled dogfood assertion stdout')\n"
        "    print('controlled dogfood assertion stderr', file=sys.stderr)\n"
        "    raise SystemExit(37)\n"
        "raise SystemExit(0)\n",
    )
    gate.write_text(
        gate.read_text(encoding="utf-8")
        + "\n\ndef loopback_check():\n"
        + "    return check('local_loopback', 'passed', 'synthetic loopback passed', requires_escalation=False)\n",
        encoding="utf-8",
    )

    v11_marker = parent / "official-v11-invoked"
    write_executable(
        candidate / "rebuild/validation/end-to-end/multi-repository/harness.py",
        "#!/bin/sh\n"
        "case \"${1:-}\" in\n"
        "  self-check) printf '{\"status\":\"passed\"}\\n' ;;\n"
        f"  run) : > '{v11_marker}' ; exit 97 ;;\n"
        "  *) exit 96 ;;\n"
        "esac\n",
    )

    bin_directory = parent / "bin"
    final_marker = parent / "exact-final-invoked"
    write_executable(
        bin_directory / "cargo",
        "#!/bin/sh\n"
        "if [ \"${1:-}\" = --version ]; then printf 'cargo 1.90.0 (fixture)\\n'; exit 0; fi\n"
        f": > '{final_marker}'\nexit 98\n",
    )
    write_executable(
        bin_directory / "codex",
        "#!/bin/sh\n"
        "if [ \"${1:-}\" = --version ]; then printf 'codex-cli 0.0.0-fixture\\n'; fi\n"
        "exit 0\n",
    )
    auth = parent / "codex-home/auth.json"
    auth.parent.mkdir(parents=True)
    auth.write_text("fixture-auth-present\n", encoding="utf-8")

    assert git(candidate, "init", "-q").returncode == 0
    assert git(candidate, "add", ".").returncode == 0
    committed = run(
        (
            "git", "-c", "user.name=Validation Fixture",
            "-c", "user.email=validation@example.invalid",
            "commit", "-qm", "fixture candidate",
        ),
        cwd=candidate,
    )
    assert committed.returncode == 0, committed.stderr

    env = os.environ.copy()
    env["PATH"] = f"{bin_directory}{os.pathsep}{env['PATH']}"
    env["CODEX_HOME"] = str(auth.parent)
    env.pop("VALIDATION_DIRTY_PROBE", None)
    return candidate, env, final_marker, v11_marker


def invoke(candidate: Path, env: dict[str, str], *arguments: str) -> subprocess.CompletedProcess[str]:
    return run((str(candidate / "rebuild/scripts/validate"), *arguments), cwd=candidate, env=env)


def assert_maintained_preflight(parent: Path) -> None:
    candidate = parent / "preflight-candidate"
    harness = candidate / "rebuild/validation/end-to-end/multi-repository/harness.py"
    harness.parent.mkdir(parents=True)
    shutil.copy2(HARNESS, harness)
    for name in ("performance.py", "performance-budgets.json", "final_evidence.py",
                 "restart_recall.py", "multi_work.py", "result_contract.py",
                 "multi_work_self_test.py"):
        shutil.copy2(HARNESS.with_name(name), harness.with_name(name))
    runner = candidate / "rebuild/scripts/validate"
    runner.parent.mkdir(parents=True)
    shutil.copy2(RUNNER, runner)
    (candidate / ".gitignore").write_text("/rebuild/.local/\n")
    assert git(candidate, "init", "-q").returncode == 0
    assert git(candidate, "add", ".").returncode == 0
    def commit(subject):
        result = run(("git", "-c", "user.name=Validation Fixture", "-c",
                      "user.email=validation@example.invalid", "commit", "-qm", subject), cwd=candidate)
        assert result.returncode == 0, result.stderr
    commit("preflight candidate")
    candidate_head = git(candidate, "rev-parse", "HEAD").stdout.strip()
    spec = importlib.util.spec_from_file_location("entrypoint_final_evidence", HARNESS.with_name("final_evidence.py"))
    assert spec and spec.loader
    final_evidence = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(final_evidence)
    gate_dir = candidate / "rebuild/.local/validation/current-gate"
    gate_dir.mkdir(parents=True)
    final_artifact = gate_dir / "final/summary.json"
    final_artifact.parent.mkdir()
    commands = []
    for index, argv in enumerate(final_evidence.maintained_final_commands(candidate)):
        directory = final_artifact.parent / str(index)
        directory.mkdir()
        stdout = directory / "stdout.log"
        stderr = directory / "stderr.log"
        stdout.write_text("")
        stderr.write_text("")
        leaf = {"argv": list(argv), "outcome": "succeeded", "exit_code": 0,
                "spawn_error": None, "termination": None,
                "stdout": str(stdout), "stderr": str(stderr)}
        (directory / "result.json").write_text(json.dumps(leaf))
        commands.append({**leaf, "artifact_directory": str(directory)})
    summary = {"schema_version": 1, "working_directory": str(candidate),
               "outcome": "succeeded", "failure_count": 0, "command_count": 4, "commands": commands}
    final_artifact.write_text(json.dumps(summary))
    environment = os.environ.copy() | final_evidence.issue_gate_binding(gate_dir, candidate_head, final_artifact)
    argv = (str(harness), "preflight", "--validated-head", candidate_head,
            "--final-artifact", str(final_artifact))
    result = run(argv, cwd=candidate, env=environment)
    value = structured_stdout(result)
    assert result.returncode == 0, (result.stderr, value)
    assert value["status"] == "passed" and value["same_gate_final_valid"] is True
    assert value["head_matches"] is True and value["worktree_clean"] is True

    def rejected(label, arguments=argv, env=environment):
        result = run(arguments, cwd=candidate, env=env)
        assert result.returncode != 0, label
        return result
    unbound_env = {key: value for key, value in environment.items()
                   if key not in {final_evidence.BINDING_PATH_ENV, final_evidence.BINDING_HASH_ENV}}
    rejected("unbound-final", env=unbound_env)
    original = final_artifact.read_bytes()
    for body in (b'{"outcome":"succeeded","failure_count":0}', b'{', b'[]'):
        final_artifact.write_bytes(body)
        # Reissue even for fabricated artifacts: semantic validation must still reject.
        changed_env = os.environ.copy() | final_evidence.issue_gate_binding(gate_dir, candidate_head, final_artifact)
        rejected("fabricated-final", env=changed_env)
    final_artifact.unlink()
    rejected("missing-final")
    final_artifact.write_bytes(original)
    environment.update(final_evidence.issue_gate_binding(gate_dir, candidate_head, final_artifact))
    other = gate_dir / "prior-final.json"
    other.write_bytes(original)
    rejected("other-final-path", arguments=(*argv[:-1], str(other)))
    changed = json.loads(original)
    changed["commands"][0].update(exit_code=7, outcome="failed")
    final_artifact.write_text(json.dumps(changed))
    rejected("changed-final-bytes")
    changed_env = os.environ.copy() | final_evidence.issue_gate_binding(gate_dir, candidate_head, final_artifact)
    rejected("failed-final-leaf-with-reissued-binding", env=changed_env)
    final_artifact.write_bytes(original)
    environment.update(final_evidence.issue_gate_binding(gate_dir, candidate_head, final_artifact))
    leaf_path = Path(commands[0]["artifact_directory"]) / "result.json"
    leaf_body = leaf_path.read_bytes()
    leaf_path.write_text('{}')
    rejected("mutated-preserved-final-leaf")
    leaf_path.write_bytes(leaf_body)

    binding_path = Path(environment[final_evidence.BINDING_PATH_ENV])
    binding_body = binding_path.read_bytes()
    for field, value in (("parent_pid", -1), ("gate_invocation", "prior-gate"),
                         ("candidate_head", "f" * 40)):
        changed_binding = json.loads(binding_body)
        changed_binding[field] = value
        binding_path.write_text(json.dumps(changed_binding))
        changed_env = environment | {final_evidence.BINDING_HASH_ENV:
                                    hashlib.sha256(binding_path.read_bytes()).hexdigest()}
        rejected(f"invalid-binding-{field}", env=changed_env)
    binding_path.write_bytes(binding_body)
    rejected("changed-binding-digest", env=environment | {final_evidence.BINDING_HASH_ENV: "f" * 64})

    validation_path = harness.parent / "validation-only.txt"
    validation_path.write_text("dirty validation")
    rejected("dirty-validation")
    rejected("obsolete-override", arguments=(*argv, "--allow-validation-changes"))
    assert git(candidate, "add", ".").returncode == 0
    commit("later candidate")
    rejected("ancestor-candidate")
    new_head = git(candidate, "rev-parse", "HEAD").stdout.strip()
    rejected("prior-candidate-final", arguments=(str(harness), "preflight", "--validated-head", new_head,
                                                 "--final-artifact", str(final_artifact)))
    output = gate_dir / "forbidden-run-output"
    result = rejected("run-independently-enforces-binding", arguments=(str(harness), "run",
        "--validated-head", new_head, "--final-artifact", str(final_artifact),
        "--output-dir", str(output), "--model", "synthetic-model"))
    assert structured_stdout(result)["status"] == "failed" and not output.exists()
    assert bytecode_artifacts(candidate) == []


def main() -> int:
    with tempfile.TemporaryDirectory(prefix="volicord-gate-entrypoint-self-test-") as directory:
        root = Path(directory)
        candidate, env, final_marker, v11_marker = make_candidate(root)

        clean = invoke(candidate, env, "admission", "--external-network", "available")
        clean_value = structured_stdout(clean)
        assert clean.returncode == 1
        assert clean_value["blocking_classification"] == "authorization_blocked"
        assert clean_value["final_command_count"] == 0
        assert clean_value["official_v11_command_count"] == 0
        assert clean_value['support_command_count'] == 0
        blocked_gate = invoke(candidate, env, 'gate', '--external-network', 'unavailable')
        blocked_capsule = structured_stdout(blocked_gate)
        assert blocked_gate.returncode == 1 and blocked_capsule['final_aggregate']['status'] == 'not_run'
        assert blocked_capsule['official_v11']['status'] == 'not_run'
        assert any(check['status'] == 'not_run' for check in blocked_capsule['admission_checks'])
        assert git(candidate, "status", "--porcelain=v1", "--untracked-files=all").stdout == ""
        assert bytecode_artifacts(candidate) == []
        assert not final_marker.exists() and not v11_marker.exists()

        original_dirty = candidate / "preexisting-dirty.txt"
        original_dirty.write_text("must remain\n", encoding="utf-8")
        dirty = invoke(candidate, env, "admission", "--external-network", "available")
        dirty_value = structured_stdout(dirty)
        initial = next(
            check for check in dirty_value["checks"]
            if check["name"] == "candidate_identity_and_clean_worktree"
        )
        assert dirty.returncode == 1
        assert initial["status"] == "environment_blocked"
        assert "?? preexisting-dirty.txt" in initial["details"]["dirty_entries"]
        assert original_dirty.read_text(encoding="utf-8") == "must remain\n"
        assert not final_marker.exists() and not v11_marker.exists()
        original_dirty.unlink()
        assert git(candidate, "status", "--porcelain=v1", "--untracked-files=all").stdout == ""

        authorized = invoke(
            candidate,
            env,
            "admission",
            "--external-network",
            "available",
            "--authorize-external-transmission",
            AUTHORIZATION_ASSERTION,
            "--authorize-provider-source-transmission",
            PROVIDER_AUTHORIZATION_ASSERTION,
            "--provider-model",
            "synthetic-model",
        )
        authorized_value = structured_stdout(authorized)
        assert authorized_value["status"] == "preflight_passed", authorized_value
        assert authorized_value['eligible'] is False and authorized_value['support_command_count'] == 0
        assert all(check['status'] == 'not_run' for check in authorized_value['checks']
                   if check['details'].get('reason') == 'diagnostic_preflight_only')

        failing_env = env.copy()
        failing_env["DOGFOOD_ASSERTIONS_FAIL"] = "1"
        failed_assertion = invoke(
            candidate,
            failing_env,
            "gate",
            "--external-network",
            "available",
            "--authorize-external-transmission",
            AUTHORIZATION_ASSERTION,
            "--authorize-provider-source-transmission",
            PROVIDER_AUTHORIZATION_ASSERTION,
            "--provider-model",
            "synthetic-model",
        )
        failed_capsule = structured_stdout(failed_assertion)
        failed_run = Path(next(line for line in failed_assertion.stderr.splitlines()
            if line.startswith("evidence capsule: ")).removeprefix("evidence capsule: ")).parent
        failed_value = json.loads((failed_run / 'admission.json').read_text())
        failed_check = next(check for check in failed_value["checks"]
            if check["name"] == "dogfood_contract_assertions")
        assert failed_assertion.returncode == 1
        assert failed_value["blocking_classification"] == "validation_failed"
        assert failed_check["status"] == "failed"
        assert failed_check["details"]["exit_code"] == 37
        assertion_artifacts = failed_run / 'admission-checks/dogfood-contract-assertions'
        result = json.loads((assertion_artifacts / "result.json").read_text(encoding="utf-8"))
        assert result["exit_code"] == 37 and result["wrapper_exit_code"] == 37
        assert (assertion_artifacts / "stdout.log").read_text(encoding="utf-8") \
            == "controlled dogfood assertion stdout\n"
        assert (assertion_artifacts / "stderr.log").read_text(encoding="utf-8") \
            == "controlled dogfood assertion stderr\n"
        assert not final_marker.exists() and not v11_marker.exists()

        probe_env = env.copy()
        probe_env["VALIDATION_DIRTY_PROBE"] = "1"
        probe = invoke(
            candidate,
            probe_env,
            "gate",
            "--external-network",
            "available",
            "--authorize-external-transmission",
            AUTHORIZATION_ASSERTION,
            "--authorize-provider-source-transmission",
            PROVIDER_AUTHORIZATION_ASSERTION,
            "--provider-model",
            "synthetic-model",
        )
        capsule = structured_stdout(probe)
        pre_final = capsule["pre_final_candidate_check"]
        generated = candidate / "admission-generated-dirty.txt"
        assert probe.returncode == 1
        assert capsule["admission_status"] == "eligible", capsule
        assert capsule["blocking_classification"] == "candidate_worktree_dirty"
        assert pre_final["status"] == "environment_blocked"
        assert pre_final["details"]["head_unchanged"] is True
        assert "?? admission-generated-dirty.txt" in pre_final["details"]["dirty_entries"]
        assert generated.is_file()
        assert not final_marker.exists() and not v11_marker.exists()
        assert bytecode_artifacts(candidate) == []

        assert_maintained_preflight(root)

    print(json.dumps({
        "status": "passed",
        "scenarios": 5,
        "maintained_v11_preflight_mutation_controls": "passed",
        "real_admission_entrypoint_invocations": 5,
        "real_final_invocations": 0,
        "official_v11_invocations": 0,
    }, indent=2, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
