#!/usr/bin/env python3
"""Exercise the maintained admission entry point in isolated Git candidates."""

from __future__ import annotations

import json
import os
from pathlib import Path
import shutil
import stat
import subprocess
import tempfile
from typing import Any, Sequence


HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[3]
RUNNER = ROOT / "rebuild/scripts/validate"
EVIDENCE_ARCHIVE = HERE / "evidence_archive.py"
EVIDENCE_ARCHIVE_VERIFIER = ROOT / "rebuild/scripts/verify-validation-archive"
GATE = HERE / "gate.py"
RESOURCE_ESTIMATE = HERE / "resource-estimate.json"
HARNESS = HERE / "harness.py"
AUTHORIZATION_ASSERTION = "v11-openai-codex-project-health-three-targets"


def write_executable(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    path.chmod(path.stat().st_mode | stat.S_IXUSR)


def run(argv: Sequence[str], *, cwd: Path, env: dict[str, str] | None = None) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        list(argv), cwd=cwd, env=env, text=True, capture_output=True, check=False
    )


def git(candidate: Path, *arguments: str) -> subprocess.CompletedProcess[str]:
    return run(("git", *arguments), cwd=candidate)


def structured_stdout(result: subprocess.CompletedProcess[str]) -> dict[str, Any]:
    try:
        value = json.loads(result.stdout)
    except json.JSONDecodeError as error:
        raise AssertionError(f"entry point did not emit JSON: {result.stdout!r}") from error
    assert isinstance(value, dict)
    return value


def bytecode_artifacts(candidate: Path) -> list[str]:
    artifacts = []
    for path in candidate.rglob("*"):
        if path.name == "__pycache__" or path.suffix in {".pyc", ".pyo"}:
            artifacts.append(path.relative_to(candidate).as_posix())
    return sorted(artifacts)


def make_candidate(parent: Path) -> tuple[Path, dict[str, str], Path, Path]:
    candidate = parent / "candidate"
    runner = candidate / "rebuild/scripts/validate"
    evidence_archive = candidate / "rebuild/validation/end-to-end/multi-repository/evidence_archive.py"
    evidence_archive_verifier = candidate / "rebuild/scripts/verify-validation-archive"
    gate = candidate / "rebuild/validation/end-to-end/multi-repository/gate.py"
    resource_estimate = candidate / "rebuild/validation/end-to-end/multi-repository/resource-estimate.json"
    runner.parent.mkdir(parents=True)
    gate.parent.mkdir(parents=True)
    shutil.copy2(RUNNER, runner)
    shutil.copy2(EVIDENCE_ARCHIVE, evidence_archive)
    shutil.copy2(EVIDENCE_ARCHIVE_VERIFIER, evidence_archive_verifier)
    shutil.copy2(GATE, gate)
    shutil.copy2(RESOURCE_ESTIMATE, resource_estimate)

    (candidate / ".gitignore").write_text("/rebuild/.local/\n", encoding="utf-8")
    manifest = candidate / "rebuild/validation/shared/fixture-manifest.json"
    manifest.parent.mkdir(parents=True)
    manifest.write_text(json.dumps({
        "schema_version": 1,
        "fixtures": [
            {"id": "v01-python", "validation_id": "V01", "content_sha256": "a" * 64},
            {"id": "v11-polyglot-medium", "validation_id": "V11", "content_sha256": "b" * 64},
        ],
    }), encoding="utf-8")
    (candidate / "rebuild/Cargo.toml").write_text(
        "[workspace]\nresolver = \"2\"\nmembers = []\n", encoding="utf-8"
    )
    (candidate / "rebuild/Cargo.lock").write_text(
        "# synthetic gate-entrypoint fixture\nversion = 4\n", encoding="utf-8"
    )

    write_executable(candidate / "rebuild/install.sh", "#!/bin/sh\nexit 0\n")
    write_executable(
        candidate / "rebuild/scripts/check-fixture-manifest",
        "#!/bin/sh\n"
        "if [ \"${VALIDATION_DIRTY_PROBE:-0}\" = 1 ]; then\n"
        "  printf 'generated by admission probe\\n' > admission-generated-dirty.txt\n"
        "fi\n"
        "exit 0\n",
    )

    v11_marker = parent / "official-v11-invoked"
    write_executable(
        candidate / "rebuild/validation/end-to-end/multi-repository/harness.py",
        "#!/bin/sh\n"
        "case \"${1:-}\" in\n"
        "  self-check) printf '{\"status\":\"passed\"}\\n' ;;\n"
        f"  run) : > '{v11_marker}' ; exit 97 ;;\n"
        "  *) exit 96 ;;\n"
        "esac\n",
    )

    bin_directory = parent / "bin"
    final_marker = parent / "exact-final-invoked"
    write_executable(
        bin_directory / "cargo",
        "#!/bin/sh\n"
        "if [ \"${1:-}\" = --version ]; then printf 'cargo 1.90.0 (fixture)\\n'; exit 0; fi\n"
        f": > '{final_marker}'\nexit 98\n",
    )
    write_executable(
        bin_directory / "codex",
        "#!/bin/sh\n"
        "if [ \"${1:-}\" = --version ]; then printf 'codex-cli 0.0.0-fixture\\n'; fi\n"
        "exit 0\n",
    )
    auth = parent / "codex-home/auth.json"
    auth.parent.mkdir(parents=True)
    auth.write_text("fixture-auth-present\n", encoding="utf-8")

    assert git(candidate, "init", "-q").returncode == 0
    assert git(candidate, "add", ".").returncode == 0
    committed = run(
        (
            "git", "-c", "user.name=Validation Fixture",
            "-c", "user.email=validation@example.invalid",
            "commit", "-qm", "fixture candidate",
        ),
        cwd=candidate,
    )
    assert committed.returncode == 0, committed.stderr

    env = os.environ.copy()
    env["PATH"] = f"{bin_directory}{os.pathsep}{env['PATH']}"
    env["CODEX_HOME"] = str(auth.parent)
    env.pop("VALIDATION_DIRTY_PROBE", None)
    return candidate, env, final_marker, v11_marker


def invoke(candidate: Path, env: dict[str, str], *arguments: str) -> subprocess.CompletedProcess[str]:
    return run((str(candidate / "rebuild/scripts/validate"), *arguments), cwd=candidate, env=env)


def assert_maintained_preflight(parent: Path) -> None:
    candidate = parent / "preflight-candidate"
    harness = candidate / "rebuild/validation/end-to-end/multi-repository/harness.py"
    harness.parent.mkdir(parents=True)
    shutil.copy2(HARNESS, harness)
    assert git(candidate, "init", "-q").returncode == 0
    assert git(candidate, "add", ".").returncode == 0
    committed = run(
        (
            "git", "-c", "user.name=Validation Fixture",
            "-c", "user.email=validation@example.invalid",
            "commit", "-qm", "preflight candidate",
        ),
        cwd=candidate,
    )
    assert committed.returncode == 0, committed.stderr
    candidate_head = git(candidate, "rev-parse", "HEAD").stdout.strip()
    final_artifact = parent / "synthetic-preflight-summary.json"
    final_artifact.write_text(
        json.dumps({"outcome": "succeeded", "failure_count": 0}), encoding="utf-8"
    )
    result = run(
        (
            str(harness), "preflight", "--validated-head", candidate_head,
            "--final-artifact", str(final_artifact),
        ),
        cwd=candidate,
        env=os.environ.copy(),
    )
    value = structured_stdout(result)
    assert result.returncode == 0, result.stderr
    assert value["status"] == "passed"
    assert value["worktree_clean"] is True
    assert value["validated_head_is_ancestor"] is True
    assert bytecode_artifacts(candidate) == []


def main() -> int:
    with tempfile.TemporaryDirectory(prefix="volicord-gate-entrypoint-self-test-") as directory:
        root = Path(directory)
        candidate, env, final_marker, v11_marker = make_candidate(root)

        clean = invoke(candidate, env, "admission", "--external-network", "available")
        clean_value = structured_stdout(clean)
        assert clean.returncode == 1
        assert clean_value["blocking_classification"] == "authorization_blocked"
        assert clean_value["final_command_count"] == 0
        assert clean_value["official_v11_command_count"] == 0
        assert git(candidate, "status", "--porcelain=v1", "--untracked-files=all").stdout == ""
        assert bytecode_artifacts(candidate) == []
        assert not final_marker.exists() and not v11_marker.exists()

        original_dirty = candidate / "preexisting-dirty.txt"
        original_dirty.write_text("must remain\n", encoding="utf-8")
        dirty = invoke(candidate, env, "admission", "--external-network", "available")
        dirty_value = structured_stdout(dirty)
        initial = next(
            check for check in dirty_value["checks"]
            if check["name"] == "candidate_identity_and_clean_worktree"
        )
        assert dirty.returncode == 1
        assert initial["status"] == "environment_blocked"
        assert "?? preexisting-dirty.txt" in initial["details"]["dirty_entries"]
        assert original_dirty.read_text(encoding="utf-8") == "must remain\n"
        assert not final_marker.exists() and not v11_marker.exists()
        original_dirty.unlink()
        assert git(candidate, "status", "--porcelain=v1", "--untracked-files=all").stdout == ""

        authorized = invoke(
            candidate,
            env,
            "admission",
            "--external-network",
            "available",
            "--authorize-external-transmission",
            AUTHORIZATION_ASSERTION,
        )
        authorized_value = structured_stdout(authorized)
        assert authorized_value["status"] == "eligible", authorized_value

        probe_env = env.copy()
        probe_env["VALIDATION_DIRTY_PROBE"] = "1"
        probe = invoke(
            candidate,
            probe_env,
            "gate",
            "--external-network",
            "available",
            "--authorize-external-transmission",
            AUTHORIZATION_ASSERTION,
        )
        capsule = structured_stdout(probe)
        pre_final = capsule["pre_final_candidate_check"]
        generated = candidate / "admission-generated-dirty.txt"
        assert probe.returncode == 1
        assert capsule["admission_status"] == "eligible", capsule
        assert capsule["blocking_classification"] == "candidate_worktree_dirty"
        assert pre_final["status"] == "environment_blocked"
        assert pre_final["details"]["head_unchanged"] is True
        assert "?? admission-generated-dirty.txt" in pre_final["details"]["dirty_entries"]
        assert generated.is_file()
        assert not final_marker.exists() and not v11_marker.exists()
        assert bytecode_artifacts(candidate) == []

        assert_maintained_preflight(root)

    print(json.dumps({
        "status": "passed",
        "scenarios": 4,
        "maintained_v11_preflight_invocations": 1,
        "real_admission_entrypoint_invocations": 4,
        "real_final_invocations": 0,
        "official_v11_invocations": 0,
    }, indent=2, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
