use crate::diagnostics::ValidationIssue;
use crate::doc_index::DocIndex;
use crate::repository::normalize_existing_root;
use crate::DOC_INDEX_PATH;
use anyhow::{Context, Result};
use std::fs;
use std::path::Path;

const ADMIN_CLI_REFERENCE_PATHS: &[&str] = &[
    "docs/en/reference/admin-cli.md",
    "docs/ko/reference/admin-cli.md",
];
const CLI_SYNOPSIS_BEGIN_MARKER: &str = "<!-- BEGIN GENERATED: volicord-cli-synopses -->";
const CLI_SYNOPSIS_END_MARKER: &str = "<!-- END GENERATED: volicord-cli-synopses -->";
#[derive(Debug, Clone)]
struct VolicordCommandExample {
    line: usize,
    command: String,
    tokens: std::result::Result<Vec<String>, String>,
}

#[derive(Debug, Clone)]
struct PendingShellCommand {
    line: usize,
    text: String,
}

#[derive(Debug, Clone)]
pub(crate) struct ActiveFence {
    marker: char,
    length: usize,
    cli_example: bool,
}

pub fn run_docs_sync(root: &Path) -> Result<DocsSyncReport> {
    let root = normalize_existing_root(root)?;
    if !root.join(DOC_INDEX_PATH).exists() {
        anyhow::bail!(
            "docs-sync must run from the repository root; missing {}",
            DOC_INDEX_PATH
        );
    }

    let generated_region = generated_cli_synopsis_region();
    let mut candidates = Vec::new();
    for relative in ADMIN_CLI_REFERENCE_PATHS {
        let path = root.join(relative);
        let contents = fs::read_to_string(&path)
            .with_context(|| format!("failed to read generated CLI owner at {}", path.display()))?;
        let updated = replace_generated_region(&contents, &generated_region)
            .with_context(|| format!("invalid generated CLI region in {relative}"))?;
        candidates.push((relative.to_string(), path, contents, updated));
    }

    let mut updated_paths = Vec::new();
    for (relative, path, contents, updated) in candidates {
        if contents == updated {
            continue;
        }
        fs::write(&path, updated).with_context(|| {
            format!("failed to update generated CLI owner at {}", path.display())
        })?;
        updated_paths.push(relative);
    }

    Ok(DocsSyncReport { updated_paths })
}

fn generated_cli_synopsis_region() -> String {
    let mut output = String::new();
    output.push_str(CLI_SYNOPSIS_BEGIN_MARKER);
    output.push('\n');
    output.push_str(
        "<!-- Generated by `cargo run -p xtask -- docs-sync`; do not edit this region. -->\n",
    );

    for syntax in volicord_command_model::public_command_syntax() {
        let command = std::iter::once("volicord")
            .chain(syntax.components().iter().map(String::as_str))
            .collect::<Vec<_>>()
            .join(" ");
        output.push_str("\n### `");
        output.push_str(&command);
        output.push_str("`\n\n```text\n");
        output.push_str(syntax.synopsis().trim_end());
        output.push('\n');
        if !syntax.arguments().is_empty() {
            output.push_str("\nArguments and options:\n");
            for argument in syntax.arguments() {
                output.push_str("  ");
                output.push_str(argument);
                output.push('\n');
            }
        }
        output.push_str("```\n");
    }

    output.push('\n');
    output.push_str(CLI_SYNOPSIS_END_MARKER);
    output
}

fn replace_generated_region(contents: &str, expected: &str) -> Result<String> {
    let range = generated_region_range(contents)?;
    let mut updated = String::with_capacity(contents.len() + expected.len());
    updated.push_str(&contents[..range.start]);
    updated.push_str(expected);
    updated.push_str(&contents[range.end..]);
    Ok(updated)
}

fn generated_region_range(contents: &str) -> Result<std::ops::Range<usize>> {
    let starts = contents
        .match_indices(CLI_SYNOPSIS_BEGIN_MARKER)
        .map(|(index, _)| index)
        .collect::<Vec<_>>();
    let ends = contents
        .match_indices(CLI_SYNOPSIS_END_MARKER)
        .map(|(index, _)| index)
        .collect::<Vec<_>>();
    if starts.len() != 1 || ends.len() != 1 {
        anyhow::bail!(
            "expected exactly one {} marker and one {} marker",
            CLI_SYNOPSIS_BEGIN_MARKER,
            CLI_SYNOPSIS_END_MARKER
        );
    }
    let start = starts[0];
    let end = ends[0];
    if end <= start {
        anyhow::bail!("generated CLI region end marker must follow its begin marker");
    }
    Ok(start..end + CLI_SYNOPSIS_END_MARKER.len())
}

pub(crate) fn validate_generated_cli_synopsis_regions(
    root: &Path,
    index: &DocIndex,
    errors: &mut Vec<ValidationIssue>,
) {
    let expected = generated_cli_synopsis_region();
    for path in ADMIN_CLI_REFERENCE_PATHS {
        if !index.indexed_paths.contains(*path) {
            continue;
        }
        let contents = match fs::read_to_string(root.join(path)) {
            Ok(contents) => contents,
            Err(error) => {
                errors.push(ValidationIssue::new(
                    *path,
                    "generated_cli.read",
                    format!("failed to read generated CLI owner: {error}"),
                ));
                continue;
            }
        };
        let range = match generated_region_range(&contents) {
            Ok(range) => range,
            Err(error) => {
                errors.push(ValidationIssue::new(
                    *path,
                    "generated_cli.markers",
                    error.to_string(),
                ));
                continue;
            }
        };
        if contents[range] != expected {
            errors.push(ValidationIssue::new(
                *path,
                "generated_cli.drift",
                "generated CLI synopsis region differs from the command model; run `cargo run -p xtask -- docs-sync`",
            ));
        }
    }
}

pub(crate) fn validate_volicord_command_examples(
    root: &Path,
    index: &DocIndex,
    errors: &mut Vec<ValidationIssue>,
) {
    for path in index
        .indexed_paths
        .iter()
        .filter(|path| path.ends_with(".md"))
    {
        let contents = match fs::read_to_string(root.join(path)) {
            Ok(contents) => contents,
            Err(error) => {
                errors.push(ValidationIssue::new(
                    path,
                    "command.read",
                    format!("failed to read Markdown file: {error}"),
                ));
                continue;
            }
        };

        for example in volicord_command_examples(&contents) {
            let result = match &example.tokens {
                Ok(tokens) => validate_volicord_command(tokens),
                Err(error) => Err(error.clone()),
            };
            if let Err(message) = result {
                errors.push(ValidationIssue::at_line(
                    path,
                    "command.invalid_example",
                    Some(example.line),
                    format!(
                        "command `{}` is not supported: {}",
                        example.command, message
                    ),
                ));
            }
        }
    }
}

fn volicord_command_examples(contents: &str) -> Vec<VolicordCommandExample> {
    let mut examples = Vec::new();
    let mut active_fence = None;
    let mut pending = None;

    for (index, line) in contents.lines().enumerate() {
        let line_number = index + 1;
        if let Some(fence) = active_fence.as_ref() {
            if is_closing_fence(line, fence) {
                active_fence = None;
                pending = None;
                continue;
            }
            if fence.cli_example {
                collect_shell_command_line(line, line_number, &mut pending, &mut examples);
            }
            continue;
        }

        if let Some(fence) = opening_fence(line) {
            active_fence = Some(fence);
        }
    }

    if let Some(pending) = pending {
        push_shell_command_candidate(pending.line, &pending.text, &mut examples);
    }

    examples
}

fn collect_shell_command_line(
    line: &str,
    line_number: usize,
    pending: &mut Option<PendingShellCommand>,
    examples: &mut Vec<VolicordCommandExample>,
) {
    let trimmed = strip_shell_prompt(line).trim();
    if pending.is_none() && (trimmed.is_empty() || trimmed.starts_with('#')) {
        return;
    }

    let (continued_text, continues) = split_shell_continuation(trimmed);
    if let Some(pending_command) = pending.as_mut() {
        if !continued_text.is_empty() {
            pending_command.text.push(' ');
            pending_command.text.push_str(continued_text);
        }
    } else {
        *pending = Some(PendingShellCommand {
            line: line_number,
            text: continued_text.to_string(),
        });
    }

    if !continues {
        if let Some(command) = pending.take() {
            push_shell_command_candidate(command.line, &command.text, examples);
        }
    }
}

fn split_shell_continuation(line: &str) -> (&str, bool) {
    let trimmed = line.trim_end();
    if trimmed.ends_with('\\') {
        (trimmed.trim_end_matches('\\').trim_end(), true)
    } else {
        (trimmed, false)
    }
}

fn push_shell_command_candidate(
    line: usize,
    command: &str,
    examples: &mut Vec<VolicordCommandExample>,
) {
    let tokens =
        shlex::split(command).ok_or_else(|| "command contains an unterminated quote".to_string());
    match &tokens {
        Ok(tokens) if volicord_command_start(tokens).is_none() => return,
        Err(_) if !starts_like_volicord_command(command) => return,
        _ => {}
    }

    examples.push(VolicordCommandExample {
        line,
        command: command.to_string(),
        tokens,
    });
}

pub(crate) fn opening_fence(line: &str) -> Option<ActiveFence> {
    let trimmed = line.trim_start();
    let marker = trimmed.chars().next()?;
    if !matches!(marker, '`' | '~') {
        return None;
    }
    let length = trimmed
        .chars()
        .take_while(|character| *character == marker)
        .count();
    if length < 3 {
        return None;
    }
    let info = trimmed[length..].trim();
    Some(ActiveFence {
        marker,
        length,
        cli_example: is_cli_example_code_info(info),
    })
}

pub(crate) fn is_closing_fence(line: &str, fence: &ActiveFence) -> bool {
    let trimmed = line.trim_start();
    let length = trimmed
        .chars()
        .take_while(|character| *character == fence.marker)
        .count();
    length >= fence.length && trimmed[length..].trim().is_empty()
}

fn is_cli_example_code_info(info: &str) -> bool {
    let normalized = info
        .trim()
        .trim_matches('{')
        .trim_matches('}')
        .split_whitespace()
        .map(|part| part.trim_start_matches('.').to_ascii_lowercase())
        .collect::<Vec<_>>();
    normalized.first().is_some_and(|language| language == "sh")
        && normalized
            .iter()
            .skip(1)
            .any(|attribute| attribute == "cli-example")
}

fn strip_shell_prompt(line: &str) -> &str {
    let trimmed = line.trim_start();
    for prompt in ["$ ", "% ", "> "] {
        if let Some(command) = trimmed.strip_prefix(prompt) {
            return command;
        }
    }
    trimmed
}

fn starts_like_volicord_command(command: &str) -> bool {
    let mut tokens = command.split_whitespace();
    let mut token = tokens.next();
    if token.is_some_and(|token| token == "env") {
        token = tokens.next();
    }
    while token.is_some_and(is_env_assignment) {
        token = tokens.next();
    }
    token.is_some_and(is_volicord_binary)
}

fn validate_volicord_command(tokens: &[String]) -> std::result::Result<(), String> {
    let Some(command_start) = volicord_command_start(tokens) else {
        return Ok(());
    };
    volicord_command_model::validate_public_invocation(tokens[command_start..].iter().cloned())
        .map_err(|error| error.to_string())
}

fn volicord_command_start(tokens: &[String]) -> Option<usize> {
    let mut index = 0;
    if tokens.first().is_some_and(|token| token == "env") {
        index += 1;
    }
    while tokens
        .get(index)
        .is_some_and(|token| is_env_assignment(token))
    {
        index += 1;
    }
    tokens
        .get(index)
        .is_some_and(|token| is_volicord_binary(token))
        .then_some(index)
}

fn is_env_assignment(token: &str) -> bool {
    let Some((name, _)) = token.split_once('=') else {
        return false;
    };
    let mut chars = name.chars();
    let Some(first) = chars.next() else {
        return false;
    };
    (first == '_' || first.is_ascii_alphabetic())
        && chars.all(|character| character == '_' || character.is_ascii_alphanumeric())
}

fn is_volicord_binary(token: &str) -> bool {
    token == "volicord"
        || token == "$VOLICORD_BIN"
        || token == "${VOLICORD_BIN}"
        || token
            .rsplit('/')
            .next()
            .is_some_and(|name| name == "volicord")
}
#[derive(Debug, Clone, Eq, PartialEq)]
pub struct DocsSyncReport {
    updated_paths: Vec<String>,
}

impl DocsSyncReport {
    pub fn updated_paths(&self) -> &[String] {
        &self.updated_paths
    }
}
