use crate::diagnostics::ValidationIssue;
use crate::doc_index::{DocIndex, DocumentContractBinding, DocumentContractRole};
use anyhow::{bail, Context, Result};
use serde_json::{Map, Value};
use std::collections::{BTreeMap, BTreeSet};
use std::fs;
use std::ops::Range;
use std::path::Path;
use volicord_types::contracts::{public_json_contract_descriptors, JsonContractDescriptor};
use volicord_types::methods::DryRunRequestPolicy;

const CORE_SCHEMA_DOC_ID: &str = "reference.api.schema-core";
const CORE_SCHEMA_CONTRACT_ID: &str = "api.schema.core";
const GENERATED_REGION_PREFIX: &str = "<!-- BEGIN GENERATED: contract-structures ";
const GENERATED_NOTICE: &str =
    "<!-- Generated by `cargo run -p xtask -- docs-sync`; do not edit this region. -->";
const PARAMS_SHAPE: &str = "params";
const RESPONSE_VARIANTS_SHAPE: &str = "response_variants";
const RESULT_SHAPE: &str = "result_body";
const REJECTION_SHAPE: &str = "rejection";
const DRY_RUN_SHAPE: &str = "dry_run";
const RESULT_BASE_SHAPE: &str = "schema_object.ToolResultBase";
const REJECTED_BASE_SHAPE: &str = "schema_object.ToolRejectedBase";
const DRY_RUN_BASE_SHAPE: &str = "schema_object.ToolDryRunBase";
const SHARED_REJECTION_SHAPE: &str = "schema_object.ToolRejectedResponse";
const SHARED_DRY_RUN_SHAPE: &str = "schema_object.ToolDryRunResponse";

#[derive(Copy, Clone, Debug, Eq, PartialEq)]
enum Language {
    English,
    Korean,
}

#[derive(Copy, Clone)]
enum TableRole {
    Request,
    Success,
    Common,
    Rejection,
    Preview,
}

#[derive(Debug)]
struct RenderedRegion {
    id: String,
    contents: String,
}

#[derive(Debug, Clone, Default)]
struct ObjectVariant {
    label: Option<String>,
    properties: BTreeMap<String, Value>,
    required: BTreeSet<String>,
}

struct CommonResponseSchemas<'a> {
    result_base: &'a Value,
    rejected_base: &'a Value,
    dry_run_base: &'a Value,
    rejection: &'a Value,
    dry_run: &'a Value,
}

pub(crate) fn sync_generated_contract_tables(root: &Path, index: &DocIndex) -> Result<Vec<String>> {
    let descriptors = descriptor_catalog();
    let common = common_response_schemas(&descriptors)?;
    let mut documents = contract_documents(index, &descriptors, &common)?;
    documents.sort_by(|left, right| left.0.cmp(&right.0));

    let mut candidates = Vec::new();
    for (path, _language, regions) in documents {
        let absolute = root.join(&path);
        let contents = fs::read_to_string(&absolute)
            .with_context(|| format!("failed to read generated contract owner at {path}"))?;
        let updated = replace_regions(&contents, &regions)
            .with_context(|| format!("invalid generated contract regions in {path}"))?;
        candidates.push((path, absolute, contents, updated));
    }

    let mut updated_paths = Vec::new();
    for (path, absolute, contents, updated) in candidates {
        if contents == updated {
            continue;
        }
        fs::write(&absolute, updated)
            .with_context(|| format!("failed to update generated contract owner at {path}"))?;
        updated_paths.push(path);
    }
    Ok(updated_paths)
}

pub(crate) fn validate_generated_contract_tables(
    root: &Path,
    index: &DocIndex,
    issues: &mut Vec<ValidationIssue>,
) {
    let descriptors = descriptor_catalog();
    let common = match common_response_schemas(&descriptors) {
        Ok(common) => common,
        Err(error) => {
            issues.push(ValidationIssue::new(
                "crates/volicord-types/src/contracts.rs",
                "generated_contract.owner",
                error.to_string(),
            ));
            return;
        }
    };
    let documents = match contract_documents(index, &descriptors, &common) {
        Ok(documents) => documents,
        Err(error) => {
            issues.push(ValidationIssue::new(
                "docs/doc-index.yaml",
                "generated_contract.owner",
                error.to_string(),
            ));
            return;
        }
    };

    for (path, _language, regions) in documents {
        let contents = match fs::read_to_string(root.join(&path)) {
            Ok(contents) => contents,
            Err(error) => {
                issues.push(ValidationIssue::new(
                    &path,
                    "generated_contract.read",
                    format!("failed to read generated contract owner: {error}"),
                ));
                continue;
            }
        };
        if let Err(error) = validate_region_inventory(&contents, &regions) {
            issues.push(ValidationIssue::new(
                &path,
                "generated_contract.region",
                error.to_string(),
            ));
            continue;
        }
        for region in regions {
            let range = match generated_region_range(&contents, &region.id) {
                Ok(range) => range,
                Err(error) => {
                    issues.push(ValidationIssue::new(
                        &path,
                        "generated_contract.region",
                        error.to_string(),
                    ));
                    continue;
                }
            };
            if contents[range] != region.contents {
                issues.push(ValidationIssue::new(
                    &path,
                    "generated_contract.drift",
                    format!(
                        "generated request or response structure for {} differs from its semantic contract descriptor; run `cargo run -p xtask -- docs-sync`",
                        region.id
                    ),
                ));
            }
        }
    }
}

fn descriptor_catalog() -> BTreeMap<String, JsonContractDescriptor> {
    public_json_contract_descriptors()
        .into_iter()
        .map(|descriptor| (descriptor.id().to_owned(), descriptor))
        .collect()
}

fn contract_documents<'a>(
    index: &DocIndex,
    descriptors: &'a BTreeMap<String, JsonContractDescriptor>,
    common: &CommonResponseSchemas<'a>,
) -> Result<Vec<(String, Language, Vec<RenderedRegion>)>> {
    let mut documents = Vec::new();
    let mut has_method_documents = false;
    for paired in index.paired_documents.values() {
        let request_bindings = paired
            .bindings_for_role(DocumentContractRole::MethodRequest)
            .cloned()
            .collect::<Vec<_>>();
        let response_bindings = paired
            .bindings_for_role(DocumentContractRole::MethodResponse)
            .cloned()
            .collect::<Vec<_>>();
        if request_bindings.is_empty() && response_bindings.is_empty() {
            continue;
        }
        if request_bindings.is_empty() || response_bindings.is_empty() {
            bail!(
                "document {} has incomplete resolved method contract bindings",
                paired.doc_id
            );
        }
        has_method_documents = true;
        for (path, language) in [
            (&paired.path_en, Language::English),
            (&paired.path_ko, Language::Korean),
        ] {
            documents.push((
                path.clone(),
                language,
                vec![
                    render_request_region(&request_bindings, descriptors, language)?,
                    render_response_region(&response_bindings, descriptors, common, language)?,
                ],
            ));
        }
    }

    let Some(core_owner) = index.paired_documents.get(CORE_SCHEMA_DOC_ID) else {
        if has_method_documents {
            bail!("docs/doc-index.yaml is missing paired owner {CORE_SCHEMA_DOC_ID}");
        }
        return Ok(documents);
    };
    let core_binding = core_owner
        .contract_bindings()
        .find(|binding| binding.contract_id.as_str() == CORE_SCHEMA_CONTRACT_ID)
        .with_context(|| {
            format!(
                "paired owner {CORE_SCHEMA_DOC_ID} has no resolved {CORE_SCHEMA_CONTRACT_ID} binding"
            )
        })?;
    let core_descriptor = descriptors
        .get(core_binding.contract_id.as_str())
        .with_context(|| {
            format!(
                "semantic contract catalog has no {} descriptor",
                core_binding.contract_id
            )
        })?;
    for (path, language) in [
        (&core_owner.path_en, Language::English),
        (&core_owner.path_ko, Language::Korean),
    ] {
        documents.push((
            path.clone(),
            language,
            vec![render_common_response_region(
                core_descriptor,
                common,
                language,
            )?],
        ));
    }
    Ok(documents)
}

fn render_request_region(
    method_bindings: &[DocumentContractBinding],
    descriptors: &BTreeMap<String, JsonContractDescriptor>,
    language: Language,
) -> Result<RenderedRegion> {
    let bindings = method_bindings
        .iter()
        .map(|binding| (binding.contract_id.as_str().to_owned(), PARAMS_SHAPE))
        .collect::<Vec<_>>();
    let id = region_id(&bindings);
    let mut body = String::new();
    for (index, (contract_id, shape)) in bindings.iter().enumerate() {
        if index > 0 {
            body.push_str("\n\n");
        }
        let descriptor = descriptors
            .get(contract_id)
            .with_context(|| format!("method document has no request descriptor {contract_id}"))?;
        let schema = exact_shape(descriptor, shape)?;
        body.push_str(&render_schema_tables(
            schema,
            language,
            TableRole::Request,
            descriptor.id(),
            shape,
        )?);
    }
    Ok(render_region(id, body))
}

fn render_response_region(
    method_bindings: &[DocumentContractBinding],
    descriptors: &BTreeMap<String, JsonContractDescriptor>,
    common: &CommonResponseSchemas<'_>,
    language: Language,
) -> Result<RenderedRegion> {
    let mut bindings = Vec::new();
    let mut response_descriptors = Vec::new();
    for binding in method_bindings {
        let contract_id = binding.contract_id.as_str();
        let descriptor = descriptors
            .get(contract_id)
            .with_context(|| format!("method document has no response descriptor {contract_id}"))?;
        for shape in [RESPONSE_VARIANTS_SHAPE, RESULT_SHAPE, REJECTION_SHAPE] {
            exact_shape(descriptor, shape)?;
            bindings.push((contract_id.to_owned(), shape));
        }
        if descriptor.example_schema(DRY_RUN_SHAPE).is_some() {
            bindings.push((contract_id.to_owned(), DRY_RUN_SHAPE));
        }
        response_descriptors.push(descriptor);
    }

    let id = region_id(&bindings);
    let mut body = String::new();
    let mut rendered_success = BTreeMap::<String, Value>::new();
    let mut shared_rejection = false;
    let mut shared_dry_run = false;
    let mut specific_shapes = Vec::new();
    let mut composition_kinds = BTreeSet::new();
    let mut previewable_responses = 0usize;
    let mut method_dry_run_contracts = Vec::new();

    for descriptor in response_descriptors {
        if let Some(method_contract) = descriptor.method_dry_run_contract() {
            method_dry_run_contracts.push(method_contract);
        }
        let success = exact_shape(descriptor, RESULT_SHAPE)?;
        let title = schema_title(success, descriptor.id(), RESULT_SHAPE)?;
        if let Some(previous) = rendered_success.insert(title.to_owned(), success.clone()) {
            if previous != *success {
                bail!(
                    "response contracts in one method document expose conflicting {title} result schemas"
                );
            }
        }

        let rejection = exact_shape(descriptor, REJECTION_SHAPE)?;
        if rejection == common.rejection {
            shared_rejection = true;
        } else {
            specific_shapes.push((
                descriptor.id(),
                REJECTION_SHAPE,
                rejection,
                TableRole::Rejection,
            ));
        }

        let rejection_title = schema_title(rejection, descriptor.id(), REJECTION_SHAPE)?;
        let composition = response_composition(exact_shape(descriptor, RESPONSE_VARIANTS_SHAPE)?)?;
        let mut expected = [title, rejection_title]
            .into_iter()
            .collect::<BTreeSet<_>>();
        if let Some(dry_run) = descriptor.example_schema(DRY_RUN_SHAPE) {
            previewable_responses += 1;
            if dry_run == common.dry_run {
                shared_dry_run = true;
            } else {
                specific_shapes.push((descriptor.id(), DRY_RUN_SHAPE, dry_run, TableRole::Preview));
            }
            expected.insert(schema_title(dry_run, descriptor.id(), DRY_RUN_SHAPE)?);
        }
        if composition.branches != expected {
            bail!(
                "semantic contract {} response_variants exposes {:?}, but its declared response shapes are {:?}",
                descriptor.id(),
                composition.branches,
                expected
            );
        }
        composition_kinds.insert(composition.combinator);
    }

    for (index, (title, schema)) in rendered_success.iter().enumerate() {
        if index > 0 {
            body.push_str("\n\n");
        }
        body.push_str(&render_schema_tables_with_title(
            schema,
            title,
            language,
            TableRole::Success,
            "method response result",
        )?);
    }

    for (contract_id, shape, schema, role) in specific_shapes {
        if !body.is_empty() {
            body.push_str("\n\n");
        }
        body.push_str(&render_schema_tables(
            schema,
            language,
            role,
            contract_id,
            shape,
        )?);
    }

    if !method_dry_run_contracts.is_empty() {
        if !body.is_empty() {
            body.push_str("\n\n");
        }
        match language {
            Language::English => {
                body.push_str("### `dry_run` request policy\n\n");
                for (method, policy) in &method_dry_run_contracts {
                    body.push_str("- `");
                    body.push_str(method.as_str());
                    body.push_str("`: ");
                    match policy {
                        DryRunRequestPolicy::Forbidden => body.push_str(
                            "a decoded request with `dry_run=true` is rejected, and the rejection preserves `base.dry_run=true` without creating a preview branch.",
                        ),
                        DryRunRequestPolicy::RegularResult => body.push_str(
                            "`dry_run=true` is accepted through the regular result branch with `base.dry_run=true`; it does not create a preview response.",
                        ),
                        DryRunRequestPolicy::Preview => body.push_str(
                            "`dry_run=true` selects the `ToolDryRunResponse` preview branch, whose `base.dry_run` is `true`.",
                        ),
                    }
                    body.push_str(
                        " `dry_run=false` or an omitted `dry_run` does not select a preview branch.\n",
                    );
                }
            }
            Language::Korean => {
                body.push_str("### `dry_run` 요청 정책\n\n");
                for (method, policy) in &method_dry_run_contracts {
                    body.push_str("- `");
                    body.push_str(method.as_str());
                    body.push_str("`: ");
                    match policy {
                        DryRunRequestPolicy::Forbidden => body.push_str(
                            "디코딩된 `dry_run=true` 요청을 거부하며, 거부 응답은 미리보기 분기를 만들지 않고 `base.dry_run=true`를 보존합니다.",
                        ),
                        DryRunRequestPolicy::RegularResult => body.push_str(
                            "`dry_run=true`를 일반 결과 분기로 처리하고 `base.dry_run=true`를 보존하며, 미리보기 응답은 만들지 않습니다.",
                        ),
                        DryRunRequestPolicy::Preview => body.push_str(
                            "`dry_run=true`가 `ToolDryRunResponse` 미리보기 분기를 선택하며, 이 분기의 `base.dry_run`은 `true`입니다.",
                        ),
                    }
                    body.push_str(
                        " `dry_run=false`이거나 `dry_run`이 생략되면 미리보기 분기를 선택하지 않습니다.\n",
                    );
                }
            }
        }
    }

    if shared_rejection || shared_dry_run {
        if !body.is_empty() {
            body.push_str("\n\n");
        }
        match language {
            Language::English => {
                body.push_str("### Shared response structures\n\n");
                let descriptor_subject = if method_bindings.len() == 1 {
                    "The response descriptor defines"
                } else {
                    "Each response descriptor defines"
                };
                body.push_str(descriptor_subject);
                body.push(' ');
                if previewable_responses == method_bindings.len() {
                    body.push_str("success, rejection, and preview as an exact `");
                } else if previewable_responses == 0 {
                    body.push_str("success and rejection as an exact `");
                } else {
                    body.push_str("its supported response branches as an exact `");
                }
                body.push_str(
                    &composition_kinds
                        .iter()
                        .cloned()
                        .collect::<Vec<_>>()
                        .join("` / `"),
                );
                body.push_str("` branch union. ");
                if previewable_responses > 0 && previewable_responses < method_bindings.len() {
                    body.push_str(
                        "Only a response descriptor that exposes preview includes that branch. ",
                    );
                }
                if shared_rejection {
                    body.push_str(
                        "The rejection branch uses the generated [`ToolRejectedResponse`](schema-core.md#common-response) structure. ",
                    );
                }
                if shared_dry_run {
                    body.push_str(
                        "When method behavior selects a preview branch, it uses the generated [`ToolDryRunResponse`](schema-core.md#common-response) structure. ",
                    );
                }
                if shared_dry_run {
                    body.push_str(
                        "Shared rejection and preview fields remain distinct from the success fields above.",
                    );
                } else {
                    body.push_str(
                        "Shared rejection fields remain distinct from the success fields above.",
                    );
                }
            }
            Language::Korean => {
                body.push_str("### 공유 응답 구조\n\n");
                if method_bindings.len() == 1 {
                    body.push_str("응답 설명자는 ");
                } else {
                    body.push_str("각 응답 설명자는 ");
                }
                if previewable_responses == method_bindings.len() {
                    body.push_str("성공, 거절, 미리보기를 정확한 `");
                } else if previewable_responses == 0 {
                    body.push_str("성공과 거절을 정확한 `");
                } else {
                    body.push_str("지원하는 응답 분기를 정확한 `");
                }
                body.push_str(
                    &composition_kinds
                        .iter()
                        .cloned()
                        .collect::<Vec<_>>()
                        .join("` / `"),
                );
                body.push_str("` 분기 union으로 정의합니다. ");
                if previewable_responses > 0 && previewable_responses < method_bindings.len() {
                    body.push_str("미리보기를 노출하는 응답 설명자만 해당 분기를 포함합니다. ");
                }
                if shared_rejection {
                    body.push_str(
                        "거절 분기는 생성된 [`ToolRejectedResponse`](schema-core.md#common-response) 구조를 사용합니다. ",
                    );
                }
                if shared_dry_run {
                    body.push_str(
                        "메서드 동작이 미리보기 분기를 선택할 때는 생성된 [`ToolDryRunResponse`](schema-core.md#common-response) 구조를 사용합니다. ",
                    );
                }
                if shared_dry_run {
                    body.push_str(
                        "공유 거절 및 미리보기 필드는 위 성공 필드와 구분된 상태로 유지됩니다.",
                    );
                } else {
                    body.push_str("공유 거절 필드는 위 성공 필드와 구분된 상태로 유지됩니다.");
                }
            }
        }
    }

    Ok(render_region(id, body))
}

struct ResponseComposition<'a> {
    combinator: String,
    branches: BTreeSet<&'a str>,
}

fn response_composition(schema: &Value) -> Result<ResponseComposition<'_>> {
    let object = schema
        .as_object()
        .context("response_variants schema must be an object")?;
    let keys = ["oneOf", "anyOf"]
        .into_iter()
        .filter(|key| object.contains_key(*key))
        .collect::<Vec<_>>();
    if keys.len() != 1 {
        bail!("response_variants schema must contain exactly one oneOf or anyOf union");
    }
    let combinator = keys[0];
    let branches = object
        .get(combinator)
        .and_then(Value::as_array)
        .with_context(|| format!("response {combinator} must be an array"))?
        .iter()
        .map(|branch| {
            branch
                .get("$ref")
                .and_then(Value::as_str)
                .map(reference_name)
                .or_else(|| branch.get("title").and_then(Value::as_str))
                .context("response branch must use a named $ref or title")
        })
        .collect::<Result<BTreeSet<_>>>()?;
    Ok(ResponseComposition {
        combinator: combinator.to_owned(),
        branches,
    })
}

fn render_common_response_region(
    descriptor: &JsonContractDescriptor,
    common: &CommonResponseSchemas<'_>,
    language: Language,
) -> Result<RenderedRegion> {
    let bindings = [
        (descriptor.id().to_owned(), RESULT_BASE_SHAPE),
        (descriptor.id().to_owned(), REJECTED_BASE_SHAPE),
        (descriptor.id().to_owned(), DRY_RUN_BASE_SHAPE),
        (descriptor.id().to_owned(), SHARED_REJECTION_SHAPE),
        (descriptor.id().to_owned(), SHARED_DRY_RUN_SHAPE),
    ];
    let id = region_id(&bindings);
    let schemas = [
        (common.result_base, TableRole::Common, RESULT_BASE_SHAPE),
        (
            common.rejected_base,
            TableRole::Rejection,
            REJECTED_BASE_SHAPE,
        ),
        (common.dry_run_base, TableRole::Preview, DRY_RUN_BASE_SHAPE),
        (
            common.rejection,
            TableRole::Rejection,
            SHARED_REJECTION_SHAPE,
        ),
        (common.dry_run, TableRole::Preview, SHARED_DRY_RUN_SHAPE),
    ];
    let mut body = String::new();
    for (index, (schema, role, shape)) in schemas.into_iter().enumerate() {
        if index > 0 {
            body.push_str("\n\n");
        }
        body.push_str(&render_schema_tables(
            schema,
            language,
            role,
            descriptor.id(),
            shape,
        )?);
    }
    Ok(render_region(id, body))
}

fn common_response_schemas<'a>(
    descriptors: &'a BTreeMap<String, JsonContractDescriptor>,
) -> Result<CommonResponseSchemas<'a>> {
    let descriptor = descriptors.get(CORE_SCHEMA_CONTRACT_ID).with_context(|| {
        format!("semantic contract catalog has no {CORE_SCHEMA_CONTRACT_ID} descriptor")
    })?;
    Ok(CommonResponseSchemas {
        result_base: exact_shape(descriptor, RESULT_BASE_SHAPE)?,
        rejected_base: exact_shape(descriptor, REJECTED_BASE_SHAPE)?,
        dry_run_base: exact_shape(descriptor, DRY_RUN_BASE_SHAPE)?,
        rejection: exact_shape(descriptor, SHARED_REJECTION_SHAPE)?,
        dry_run: exact_shape(descriptor, SHARED_DRY_RUN_SHAPE)?,
    })
}

fn exact_shape<'a>(descriptor: &'a JsonContractDescriptor, shape: &str) -> Result<&'a Value> {
    descriptor.example_schema(shape).with_context(|| {
        format!(
            "semantic contract {} has no exact {shape} schema",
            descriptor.id()
        )
    })
}

fn region_id(bindings: &[(String, &str)]) -> String {
    let bindings = bindings
        .iter()
        .map(|(contract, shape)| format!("{contract}[{shape}]"))
        .collect::<Vec<_>>()
        .join(" ");
    format!("contract-structures {bindings}")
}

fn render_region(id: String, body: String) -> RenderedRegion {
    let contents = format!(
        "<!-- BEGIN GENERATED: {id} -->\n{GENERATED_NOTICE}\n\n{body}\n<!-- END GENERATED: {id} -->"
    );
    RenderedRegion { id, contents }
}

fn replace_regions(contents: &str, regions: &[RenderedRegion]) -> Result<String> {
    let actual = generated_contract_region_ids(contents)?;
    if actual.len() != regions.len() {
        bail!(
            "generated contract region count does not match the document owner; expected {}, found {}",
            regions.len(),
            actual.len()
        );
    }
    let mut updated = contents.to_owned();
    for region in regions {
        let owner = region_owner_contracts(&region.id)?;
        let matching = actual
            .iter()
            .filter(|actual_id| {
                region_owner_contracts(actual_id).is_ok_and(|actual_owner| actual_owner == owner)
            })
            .collect::<Vec<_>>();
        if matching.len() != 1 {
            bail!(
                "expected exactly one generated contract region for owner contracts {:?}",
                owner
            );
        }
        let range = generated_region_range(&updated, matching[0])?;
        updated.replace_range(range, &region.contents);
    }
    validate_region_inventory(&updated, regions)?;
    Ok(updated)
}

fn region_owner_contracts(id: &str) -> Result<BTreeSet<&str>> {
    let bindings = id
        .strip_prefix("contract-structures ")
        .context("generated contract region has an invalid prefix")?;
    bindings
        .split_whitespace()
        .map(|binding| {
            binding
                .split_once('[')
                .map(|(contract, _)| contract)
                .context("generated contract binding has no shape")
        })
        .collect()
}

fn validate_region_inventory(contents: &str, regions: &[RenderedRegion]) -> Result<()> {
    let expected = regions
        .iter()
        .map(|region| region.id.clone())
        .collect::<BTreeSet<_>>();
    let actual = generated_contract_region_ids(contents)?;
    if actual != expected {
        let missing = expected.difference(&actual).cloned().collect::<Vec<_>>();
        let unexpected = actual.difference(&expected).cloned().collect::<Vec<_>>();
        bail!(
            "generated contract region bindings do not match the document owner; missing {:?}, unexpected {:?}",
            missing,
            unexpected
        );
    }
    Ok(())
}

fn generated_contract_region_ids(contents: &str) -> Result<BTreeSet<String>> {
    let mut ids = BTreeSet::new();
    for line in contents.lines() {
        let Some(rest) = line.strip_prefix(GENERATED_REGION_PREFIX) else {
            continue;
        };
        let Some(id) = rest.strip_suffix(" -->") else {
            bail!("generated contract begin marker is malformed: {line}");
        };
        let id = format!("contract-structures {id}");
        if !ids.insert(id.clone()) {
            bail!("generated contract region {id} is repeated");
        }
    }
    Ok(ids)
}

fn generated_region_range(contents: &str, id: &str) -> Result<Range<usize>> {
    let begin = format!("<!-- BEGIN GENERATED: {id} -->");
    let end = format!("<!-- END GENERATED: {id} -->");
    let starts = contents
        .match_indices(&begin)
        .map(|(index, _)| index)
        .collect::<Vec<_>>();
    let ends = contents
        .match_indices(&end)
        .map(|(index, _)| index)
        .collect::<Vec<_>>();
    if starts.len() != 1 || ends.len() != 1 {
        bail!("expected exactly one {begin} marker and one {end} marker");
    }
    if ends[0] <= starts[0] {
        bail!("generated contract region end marker must follow its begin marker for {id}");
    }
    Ok(starts[0]..ends[0] + end.len())
}

fn render_schema_tables(
    schema: &Value,
    language: Language,
    role: TableRole,
    contract_id: &str,
    shape: &str,
) -> Result<String> {
    let title = schema_title(schema, contract_id, shape)?;
    render_schema_tables_with_title(
        schema,
        title,
        language,
        role,
        &format!("{contract_id} shape {shape}"),
    )
}

fn render_schema_tables_with_title(
    schema: &Value,
    title: &str,
    language: Language,
    role: TableRole,
    owner_label: &str,
) -> Result<String> {
    let variants = object_variants(schema)
        .with_context(|| format!("unsupported generated structure for {owner_label}"))?;
    let mut output = String::new();
    for (index, variant) in variants.iter().enumerate() {
        if index > 0 {
            output.push_str("\n\n");
        }
        let display_title = variant
            .label
            .as_deref()
            .filter(|label| *label != title)
            .map_or_else(|| title.to_owned(), |label| format!("{title}: {label}"));
        render_table_heading(&mut output, &display_title, language, role);
        for required in &variant.required {
            if !variant.properties.contains_key(required) {
                bail!("{owner_label} marks {required} required but exposes no matching property");
            }
        }
        for (field, property) in &variant.properties {
            let nullable = schema_allows_null(property, schema, &mut BTreeSet::new())?;
            let field_type = schema_type(property, schema)?;
            output.push_str("| `");
            output.push_str(field);
            output.push_str("` | ");
            output.push_str(required_label(language, variant.required.contains(field)));
            output.push_str(" | ");
            output.push_str(required_label(language, nullable));
            output.push_str(" | `");
            output.push_str(&field_type);
            output.push_str("` |\n");
        }
        output.pop();
    }
    Ok(output)
}

fn render_table_heading(output: &mut String, title: &str, language: Language, role: TableRole) {
    let suffix = match (language, role) {
        (Language::English, TableRole::Request | TableRole::Common) => "fields",
        (Language::English, TableRole::Success) => "success fields",
        (Language::English, TableRole::Rejection) => "rejection fields",
        (Language::English, TableRole::Preview) => "preview fields",
        (Language::Korean, TableRole::Request | TableRole::Common) => "필드",
        (Language::Korean, TableRole::Success) => "성공 필드",
        (Language::Korean, TableRole::Rejection) => "거절 필드",
        (Language::Korean, TableRole::Preview) => "미리보기 필드",
    };
    output.push_str("### `");
    output.push_str(title);
    output.push_str("` ");
    output.push_str(suffix);
    output.push_str("\n\n");
    match language {
        Language::English => {
            output.push_str("| Field | Required | Nullable | Type |\n");
        }
        Language::Korean => {
            output.push_str("| 필드 | 필수 | Null 허용 | 형식 |\n");
        }
    }
    output.push_str("|---|---|---|---|\n");
}

fn required_label(language: Language, value: bool) -> &'static str {
    match (language, value) {
        (Language::English, true) => "yes",
        (Language::English, false) => "no",
        (Language::Korean, true) => "예",
        (Language::Korean, false) => "아니요",
    }
}

fn schema_title<'a>(schema: &'a Value, contract_id: &str, shape: &str) -> Result<&'a str> {
    schema
        .get("title")
        .and_then(Value::as_str)
        .with_context(|| format!("semantic contract {contract_id} shape {shape} has no title"))
}

fn object_variants(schema: &Value) -> Result<Vec<ObjectVariant>> {
    let mut stack = BTreeSet::new();
    let mut variants = object_variants_inner(schema, schema, &mut stack)?;
    if variants.is_empty() {
        bail!("object schema exposes no non-null structural variant");
    }
    if variants.len() == 1 {
        variants[0].label = None;
    }
    Ok(variants)
}

fn object_variants_inner(
    schema: &Value,
    root: &Value,
    stack: &mut BTreeSet<String>,
) -> Result<Vec<ObjectVariant>> {
    let object = schema
        .as_object()
        .context("JSON Schema node must be an object")?;
    if let Some(reference) = object.get("$ref").and_then(Value::as_str) {
        let inserted = stack.insert(reference.to_owned());
        if !inserted {
            bail!("recursive object schema reference {reference} is unsupported");
        }
        let target = resolve_reference(root, reference)?;
        let mut variants = object_variants_inner(target, root, stack)?;
        stack.remove(reference);
        let label = reference_name(reference).to_owned();
        for variant in &mut variants {
            if variant.label.is_none() {
                variant.label = Some(label.clone());
            }
        }
        return Ok(variants);
    }

    let has_object_shape = object.get("type").is_some_and(|kind| kind == "object")
        || object.contains_key("properties")
        || object.contains_key("additionalProperties");
    let mut direct = direct_object_variant(object)?;
    if object.contains_key("allOf") || object.contains_key("oneOf") || object.contains_key("anyOf")
    {
        direct.label = None;
    }
    let mut variants = vec![direct];

    if let Some(all_of) = object.get("allOf") {
        let branches = all_of.as_array().context("allOf must be an array")?;
        for branch in branches {
            let branch_variants = object_variants_inner(branch, root, stack)?;
            variants = merge_variant_sets(variants, branch_variants)?;
        }
    }

    let union_key = ["oneOf", "anyOf"]
        .into_iter()
        .filter(|key| object.contains_key(*key))
        .collect::<Vec<_>>();
    if union_key.len() > 1 {
        bail!("object schema cannot combine oneOf and anyOf at the same level");
    }
    if let Some(key) = union_key.first() {
        let branches = object
            .get(*key)
            .and_then(Value::as_array)
            .with_context(|| format!("{key} must be an array"))?;
        let mut union_variants = Vec::new();
        for branch in branches {
            if schema_allows_only_null(branch, root, &mut BTreeSet::new())? {
                continue;
            }
            union_variants.extend(object_variants_inner(branch, root, stack)?);
        }
        variants = merge_variant_sets(variants, union_variants)?;
    } else if !has_object_shape && !object.contains_key("allOf") {
        bail!("expected an object, $ref, allOf, oneOf, or anyOf schema");
    }

    let root_label = object
        .get("title")
        .and_then(Value::as_str)
        .map(str::to_owned);
    if variants.len() > 1 {
        for variant in &mut variants {
            if variant.label.is_none() {
                variant.label.clone_from(&root_label);
            }
        }
    }
    Ok(variants)
}

fn direct_object_variant(object: &Map<String, Value>) -> Result<ObjectVariant> {
    let properties = match object.get("properties") {
        Some(properties) => properties
            .as_object()
            .context("object properties must be a mapping")?
            .iter()
            .map(|(name, schema)| (name.clone(), schema.clone()))
            .collect(),
        None => BTreeMap::new(),
    };
    let required = match object.get("required") {
        Some(required) => required
            .as_array()
            .context("object required must be an array")?
            .iter()
            .map(|value| {
                value
                    .as_str()
                    .map(str::to_owned)
                    .context("required entries must be strings")
            })
            .collect::<Result<BTreeSet<_>>>()?,
        None => BTreeSet::new(),
    };
    Ok(ObjectVariant {
        label: object
            .get("title")
            .and_then(Value::as_str)
            .map(str::to_owned),
        properties,
        required,
    })
}

fn merge_variant_sets(
    left: Vec<ObjectVariant>,
    right: Vec<ObjectVariant>,
) -> Result<Vec<ObjectVariant>> {
    if right.is_empty() {
        bail!("schema combinator exposes no non-null object variants");
    }
    let mut merged = Vec::new();
    for left_variant in &left {
        for right_variant in &right {
            merged.push(merge_variants(left_variant, right_variant)?);
        }
    }
    Ok(merged)
}

fn merge_variants(left: &ObjectVariant, right: &ObjectVariant) -> Result<ObjectVariant> {
    let mut merged = left.clone();
    for (name, schema) in &right.properties {
        if let Some(previous) = merged.properties.insert(name.clone(), schema.clone()) {
            if previous != *schema {
                bail!("composed object defines conflicting schemas for property {name}");
            }
        }
    }
    merged.required.extend(right.required.iter().cloned());
    merged.label = match (&left.label, &right.label) {
        (Some(left), Some(right)) if left != right => Some(format!("{left} + {right}")),
        (Some(label), _) | (_, Some(label)) => Some(label.clone()),
        (None, None) => None,
    };
    Ok(merged)
}

fn schema_allows_null(schema: &Value, root: &Value, stack: &mut BTreeSet<String>) -> Result<bool> {
    if schema.is_boolean() {
        return Ok(schema == &Value::Bool(true));
    }
    let object = schema
        .as_object()
        .context("JSON Schema node must be an object or boolean")?;
    if object.get("const").is_some_and(Value::is_null) {
        return Ok(true);
    }
    if object
        .get("enum")
        .and_then(Value::as_array)
        .is_some_and(|values| values.iter().any(Value::is_null))
    {
        return Ok(true);
    }
    if object.get("type").is_some_and(|kind| {
        kind == "null"
            || kind
                .as_array()
                .is_some_and(|kinds| kinds.iter().any(|kind| kind == "null"))
    }) {
        return Ok(true);
    }
    if let Some(reference) = object.get("$ref").and_then(Value::as_str) {
        if !stack.insert(reference.to_owned()) {
            bail!("recursive nullable reference {reference} is unsupported");
        }
        let result = schema_allows_null(resolve_reference(root, reference)?, root, stack);
        stack.remove(reference);
        return result;
    }
    for key in ["anyOf", "oneOf"] {
        if let Some(branches) = object.get(key) {
            let branches = branches
                .as_array()
                .with_context(|| format!("{key} must be an array"))?;
            for branch in branches {
                if schema_allows_null(branch, root, stack)? {
                    return Ok(true);
                }
            }
        }
    }
    if let Some(branches) = object.get("allOf") {
        let branches = branches.as_array().context("allOf must be an array")?;
        if !branches.is_empty()
            && branches
                .iter()
                .map(|branch| schema_allows_null(branch, root, stack))
                .collect::<Result<Vec<_>>>()?
                .into_iter()
                .all(|allows| allows)
        {
            return Ok(true);
        }
    }
    Ok(false)
}

fn schema_allows_only_null(
    schema: &Value,
    root: &Value,
    stack: &mut BTreeSet<String>,
) -> Result<bool> {
    if schema == &Value::Bool(false) {
        return Ok(false);
    }
    let object = schema
        .as_object()
        .context("JSON Schema node must be an object")?;
    if object.get("const").is_some_and(Value::is_null)
        || object.get("type").is_some_and(|kind| kind == "null")
    {
        return Ok(true);
    }
    if let Some(values) = object.get("enum").and_then(Value::as_array) {
        return Ok(!values.is_empty() && values.iter().all(Value::is_null));
    }
    if let Some(kinds) = object.get("type").and_then(Value::as_array) {
        return Ok(!kinds.is_empty() && kinds.iter().all(|kind| kind == "null"));
    }
    if let Some(reference) = object.get("$ref").and_then(Value::as_str) {
        if !stack.insert(reference.to_owned()) {
            bail!("recursive null-only reference {reference} is unsupported");
        }
        let result = schema_allows_only_null(resolve_reference(root, reference)?, root, stack);
        stack.remove(reference);
        return result;
    }
    Ok(false)
}

fn schema_type(schema: &Value, root: &Value) -> Result<String> {
    if let Some(allowed) = schema.as_bool() {
        return Ok(if allowed { "any" } else { "never" }.to_owned());
    }
    let object = schema
        .as_object()
        .context("JSON Schema node must be an object or boolean")?;
    if let Some(reference) = object.get("$ref").and_then(Value::as_str) {
        return Ok(reference_name(reference).to_owned());
    }
    if let Some(constant) = object.get("const") {
        return Ok(format!("const({})", compact_json(constant)?));
    }
    if let Some(values) = object.get("enum").and_then(Value::as_array) {
        let values = values
            .iter()
            .filter(|value| !value.is_null())
            .map(compact_json)
            .collect::<Result<Vec<_>>>()?;
        if values.is_empty() {
            return Ok("null".to_owned());
        }
        let primitive = object
            .get("type")
            .and_then(Value::as_str)
            .filter(|kind| *kind != "null")
            .map(|kind| format!("{kind} "));
        return Ok(format!(
            "{}enum({})",
            primitive.unwrap_or_default(),
            values.join(" | ")
        ));
    }
    if object.get("type").is_some_and(|kind| kind == "array") || object.contains_key("items") {
        let items = object
            .get("items")
            .context("array schema has no items schema")?;
        return Ok(format!("{}[]", schema_type(items, root)?));
    }

    for key in ["anyOf", "oneOf"] {
        if let Some(branches) = object.get(key) {
            let branches = branches
                .as_array()
                .with_context(|| format!("{key} must be an array"))?;
            let mut types = BTreeSet::new();
            for branch in branches {
                if schema_allows_only_null(branch, root, &mut BTreeSet::new())? {
                    continue;
                }
                types.insert(schema_type(branch, root)?);
            }
            if types.is_empty() {
                return Ok("null".to_owned());
            }
            return Ok(types.into_iter().collect::<Vec<_>>().join(" | "));
        }
    }
    if let Some(branches) = object.get("allOf") {
        let branches = branches.as_array().context("allOf must be an array")?;
        let types = branches
            .iter()
            .map(|branch| schema_type(branch, root))
            .collect::<Result<BTreeSet<_>>>()?;
        if !types.is_empty() {
            return Ok(types.into_iter().collect::<Vec<_>>().join(" & "));
        }
    }
    if let Some(kind) = object.get("type").and_then(Value::as_str) {
        if kind == "object" {
            if let Some(additional) = object.get("additionalProperties") {
                if additional.is_object() {
                    return Ok(format!(
                        "object<string, {}>",
                        schema_type(additional, root)?
                    ));
                }
            }
        }
        return Ok(kind.to_owned());
    }
    if let Some(kinds) = object.get("type").and_then(Value::as_array) {
        let kinds = kinds
            .iter()
            .map(|kind| kind.as_str().context("schema type entries must be strings"))
            .collect::<Result<BTreeSet<_>>>()?
            .into_iter()
            .filter(|kind| *kind != "null")
            .collect::<Vec<_>>();
        if !kinds.is_empty() {
            return Ok(kinds.join(" | "));
        }
    }
    if object.contains_key("properties") || object.contains_key("additionalProperties") {
        return Ok("object".to_owned());
    }
    bail!("unsupported property schema {schema}")
}

fn compact_json(value: &Value) -> Result<String> {
    serde_json::to_string(value).context("schema literal should serialize")
}

fn resolve_reference<'a>(root: &'a Value, reference: &str) -> Result<&'a Value> {
    let pointer = reference
        .strip_prefix('#')
        .with_context(|| format!("only local schema references are supported: {reference}"))?;
    root.pointer(pointer)
        .with_context(|| format!("schema reference {reference} does not resolve"))
}

fn reference_name(reference: &str) -> &str {
    reference.rsplit('/').next().unwrap_or(reference)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::doc_index::{ContractId, PairedDocument};
    use jsonschema::{Draft, JSONSchema};
    use serde_json::json;
    use volicord_types::contracts::JsonExampleShape;
    use volicord_types::methods::{MethodResponseBranch, PUBLIC_METHOD_CONTRACTS};

    fn binding(id: &str, role: DocumentContractRole) -> DocumentContractBinding {
        DocumentContractBinding {
            contract_id: ContractId::parse(id.to_owned()).expect("synthetic contract id"),
            role,
        }
    }

    fn paired_document(
        doc_id: &str,
        path: &str,
        bindings: impl IntoIterator<Item = DocumentContractBinding>,
    ) -> PairedDocument {
        PairedDocument {
            doc_id: doc_id.to_owned(),
            path_en: format!("docs/en/{path}"),
            path_ko: format!("docs/ko/{path}"),
            contract_bindings: bindings.into_iter().collect(),
        }
    }

    fn descriptor(id: &str, shape: JsonExampleShape, schema: Value) -> JsonContractDescriptor {
        JsonContractDescriptor::from_owner_schema(
            id,
            schema.clone(),
            Default::default(),
            Vec::new(),
        )
        .with_example_schema(shape, schema)
    }

    fn common_schemas() -> (Value, Value, Value) {
        (
            json!({
                "title": "ToolResultBase",
                "type": "object",
                "required": ["response_kind"],
                "properties": {"response_kind": {"type": "string"}}
            }),
            json!({
                "title": "ToolRejectedResponse",
                "type": "object",
                "required": ["base", "errors"],
                "properties": {
                    "base": {"$ref": "#/definitions/ToolResultBase"},
                    "errors": {"type": "array", "items": {"type": "string"}}
                },
                "definitions": {
                    "ToolResultBase": {
                        "type": "object",
                        "required": ["response_kind"],
                        "properties": {"response_kind": {"type": "string"}}
                    }
                }
            }),
            json!({
                "title": "ToolDryRunResponse",
                "type": "object",
                "required": ["base", "dry_run_summary"],
                "properties": {
                    "base": {"type": "object"},
                    "dry_run_summary": {"type": "object"}
                }
            }),
        )
    }

    fn response_descriptor(
        result: Value,
        rejection: Value,
        dry_run: Value,
    ) -> JsonContractDescriptor {
        let result_title = result["title"].as_str().expect("result title");
        let rejection_title = rejection["title"].as_str().expect("rejection title");
        let dry_run_title = dry_run["title"].as_str().expect("dry-run title");
        JsonContractDescriptor::from_owner_schema(
            "api.method.alpha.response",
            json!({"title": "AlphaResponse", "oneOf": []}),
            Default::default(),
            Vec::new(),
        )
        .with_example_schema(
            JsonExampleShape::MethodResponseVariants,
            json!({
                "title": "AlphaResponse",
                "anyOf": [
                    {"$ref": format!("#/definitions/{result_title}")},
                    {"$ref": format!("#/definitions/{rejection_title}")},
                    {"$ref": format!("#/definitions/{dry_run_title}")}
                ]
            }),
        )
        .with_example_schema(JsonExampleShape::MethodResultBody, result)
        .with_example_schema(JsonExampleShape::MethodRejection, rejection)
        .with_example_schema(JsonExampleShape::MethodDryRun, dry_run)
    }

    fn result_or_rejected_descriptor(result: Value, rejection: Value) -> JsonContractDescriptor {
        let result_title = result["title"].as_str().expect("result title");
        let rejection_title = rejection["title"].as_str().expect("rejection title");
        JsonContractDescriptor::from_owner_schema(
            "api.method.alpha.response",
            json!({"title": "AlphaResponse", "oneOf": []}),
            Default::default(),
            Vec::new(),
        )
        .with_example_schema(
            JsonExampleShape::MethodResponseVariants,
            json!({
                "title": "AlphaResponse",
                "anyOf": [
                    {"$ref": format!("#/definitions/{result_title}")},
                    {"$ref": format!("#/definitions/{rejection_title}")}
                ]
            }),
        )
        .with_example_schema(JsonExampleShape::MethodResultBody, result)
        .with_example_schema(JsonExampleShape::MethodRejection, rejection)
    }

    #[test]
    fn non_previewable_response_region_omits_preview_binding_and_prose() {
        let (base, rejection, dry_run) = common_schemas();
        let result = json!({
            "title": "AlphaResult",
            "type": "object",
            "required": ["base", "value"],
            "properties": {
                "base": {"type": "object"},
                "value": {"type": "string"}
            }
        });
        let response = result_or_rejected_descriptor(result, rejection.clone());
        let mut descriptors = BTreeMap::new();
        descriptors.insert(response.id().to_owned(), response);
        let response_binding = binding(
            "api.method.alpha.response",
            DocumentContractRole::MethodResponse,
        );

        let rendered = render_response_region(
            &[response_binding],
            &descriptors,
            &CommonResponseSchemas {
                result_base: &base,
                rejected_base: &base,
                dry_run_base: &base,
                rejection: &rejection,
                dry_run: &dry_run,
            },
            Language::English,
        )
        .expect("result-or-rejected response region");

        assert!(!rendered.id.contains(DRY_RUN_SHAPE));
        assert!(!rendered.contents.contains("ToolDryRunResponse"));
        assert!(rendered
            .contents
            .contains("success and rejection as an exact `anyOf` branch union"));
    }

    #[test]
    fn compiled_response_schemas_match_exact_branch_decoding() {
        let rejection = json!({
            "base": {
                "response_kind": "rejected",
                "effect_kind": "no_effect",
                "dry_run": false,
                "state_version": 7,
                "disclosure": {
                    "guarantee_class": "authority_record",
                    "guarantees": [],
                    "non_guarantees": []
                },
                "events": []
            },
            "errors": [{
                "category": "rejected",
                "code": "VALIDATION_FAILED",
                "message": "request validation failed",
                "retryable": false,
                "details": null
            }]
        });
        let preview = json!({
            "base": {
                "response_kind": "dry_run",
                "effect_kind": "no_effect",
                "dry_run": true,
                "state_version": 7,
                "disclosure": {
                    "guarantee_class": "authority_record",
                    "guarantees": [],
                    "non_guarantees": []
                },
                "events": []
            },
            "dry_run_summary": {
                "planned_effects": [],
                "would_blockers": [],
                "would_errors": [],
                "next_actions": [],
                "diagnostics": []
            }
        });

        for contract in PUBLIC_METHOD_CONTRACTS {
            let schema = contract.response_schema();
            let compiled = JSONSchema::options()
                .with_draft(Draft::Draft7)
                .compile(&schema)
                .unwrap_or_else(|error| {
                    panic!(
                        "{} response schema should compile: {error}",
                        contract.method().as_str()
                    )
                });
            assert!(compiled.is_valid(&rejection));
            assert!(contract.accepts_response(&rejection));

            let supports_preview = contract.supports_response_branch(MethodResponseBranch::DryRun);
            assert_eq!(compiled.is_valid(&preview), supports_preview);
            assert_eq!(contract.accepts_response(&preview), supports_preview);

            let mut invalid = Vec::new();
            for (pointer, value) in [
                ("/base/response_kind", json!("result")),
                ("/base/effect_kind", json!("core_committed")),
            ] {
                let mut instance = rejection.clone();
                *instance.pointer_mut(pointer).expect("rejection pointer") = value;
                invalid.push(instance);
            }
            for (pointer, value) in [
                ("/base/response_kind", json!("rejected")),
                ("/base/effect_kind", json!("read_only")),
                ("/base/dry_run", json!(false)),
            ] {
                let mut instance = preview.clone();
                *instance.pointer_mut(pointer).expect("preview pointer") = value;
                invalid.push(instance);
            }
            for mut instance in [rejection.clone(), preview.clone()] {
                instance["base"]["unknown_base_field"] = json!(true);
                invalid.push(instance);
            }
            for mut instance in [rejection.clone(), preview.clone()] {
                instance["unknown_branch_field"] = json!(true);
                invalid.push(instance);
            }
            let mut hybrid = rejection.clone();
            hybrid["dry_run_summary"] = preview["dry_run_summary"].clone();
            invalid.push(hybrid);

            for instance in invalid {
                assert!(
                    !compiled.is_valid(&instance),
                    "{} schema accepted invalid response {instance}",
                    contract.method().as_str()
                );
                assert!(
                    !contract.accepts_response(&instance),
                    "{} decoder accepted invalid response {instance}",
                    contract.method().as_str()
                );
            }
        }
    }

    #[test]
    fn generated_method_dry_run_prose_follows_the_canonical_policy() {
        let descriptors = descriptor_catalog();
        let common = common_response_schemas(&descriptors).expect("common response schemas");

        for contract in PUBLIC_METHOD_CONTRACTS {
            for contract_id in [
                contract.request_contract_id(),
                contract.response_contract_id(),
            ] {
                assert_eq!(
                    descriptors
                        .get(contract_id)
                        .expect("public method descriptor")
                        .method_dry_run_contract(),
                    Some((contract.method(), contract.dry_run_policy())),
                    "{} descriptor must carry its canonical dry-run policy",
                    contract_id
                );
            }

            let response_binding = binding(
                contract.response_contract_id(),
                DocumentContractRole::MethodResponse,
            );
            let english = render_response_region(
                std::slice::from_ref(&response_binding),
                &descriptors,
                &common,
                Language::English,
            )
            .expect("English method response region");
            let korean = render_response_region(
                std::slice::from_ref(&response_binding),
                &descriptors,
                &common,
                Language::Korean,
            )
            .expect("Korean method response region");

            assert!(english
                .contents
                .contains(&format!("- `{}`:", contract.method().as_str())));
            assert!(korean
                .contents
                .contains(&format!("- `{}`:", contract.method().as_str())));
            let (english_policy, korean_policy) = match contract.dry_run_policy() {
                DryRunRequestPolicy::Forbidden => (
                    "decoded request with `dry_run=true` is rejected",
                    "디코딩된 `dry_run=true` 요청을 거부",
                ),
                DryRunRequestPolicy::RegularResult => (
                    "accepted through the regular result branch",
                    "일반 결과 분기로 처리",
                ),
                DryRunRequestPolicy::Preview => (
                    "selects the `ToolDryRunResponse` preview branch",
                    "`ToolDryRunResponse` 미리보기 분기를 선택",
                ),
            };
            assert!(
                english.contents.contains(english_policy),
                "{} English generated policy prose disagrees with the canonical declaration",
                contract.method().as_str()
            );
            assert!(
                korean.contents.contains(korean_policy),
                "{} Korean generated policy prose disagrees with the canonical declaration",
                contract.method().as_str()
            );
        }
    }

    #[test]
    fn request_table_generation_remains_schema_derived() {
        let schema = json!({
            "title": "AlphaRequest",
            "type": "object",
            "required": ["snake_case"],
            "properties": {
                "optional_value": {"type": ["string", "null"]},
                "snake_case": {"type": "string"}
            }
        });
        let rendered = render_schema_tables(
            &schema,
            Language::English,
            TableRole::Request,
            "api.method.alpha.request",
            PARAMS_SHAPE,
        )
        .expect("request table");

        assert!(rendered.contains("| `optional_value` | no | yes | `string` |"));
        assert!(rendered.contains("| `snake_case` | yes | no | `string` |"));
    }

    #[test]
    fn response_field_changes_produce_deterministic_drift() {
        let original = json!({
            "title": "AlphaResult",
            "type": "object",
            "required": ["base", "count"],
            "properties": {
                "base": {"type": "object"},
                "count": {"type": "integer"}
            }
        });
        let changes = [
            json!({
                "title": "AlphaResult",
                "type": "object",
                "required": ["base", "count", "added"],
                "properties": {
                    "added": {"type": "string"},
                    "base": {"type": "object"},
                    "count": {"type": "integer"}
                }
            }),
            json!({
                "title": "AlphaResult",
                "type": "object",
                "required": ["base"],
                "properties": {"base": {"type": "object"}}
            }),
            json!({
                "title": "AlphaResult",
                "type": "object",
                "required": ["base"],
                "properties": {
                    "base": {"type": "object"},
                    "count": {"type": "integer"}
                }
            }),
            json!({
                "title": "AlphaResult",
                "type": "object",
                "required": ["base", "count"],
                "properties": {
                    "base": {"type": "object"},
                    "count": {"type": ["integer", "null"]}
                }
            }),
            json!({
                "title": "AlphaResult",
                "type": "object",
                "required": ["base", "count"],
                "properties": {
                    "base": {"type": "object"},
                    "count": {"type": "string"}
                }
            }),
        ];
        let expected = render_schema_tables(
            &original,
            Language::English,
            TableRole::Success,
            "api.method.alpha.response",
            RESULT_SHAPE,
        )
        .expect("original response");
        for changed in changes {
            let rendered = render_schema_tables(
                &changed,
                Language::English,
                TableRole::Success,
                "api.method.alpha.response",
                RESULT_SHAPE,
            )
            .expect("changed response");
            assert_ne!(rendered, expected);
            assert_eq!(
                rendered,
                render_schema_tables(
                    &changed,
                    Language::English,
                    TableRole::Success,
                    "api.method.alpha.response",
                    RESULT_SHAPE,
                )
                .expect("deterministic changed response")
            );
        }
    }

    #[test]
    fn flattened_common_result_fields_are_composed() {
        let schema = json!({
            "title": "AlphaResult",
            "allOf": [
                {"$ref": "#/definitions/CommonResult"},
                {
                    "type": "object",
                    "required": ["method_value"],
                    "properties": {"method_value": {"type": "string"}}
                }
            ],
            "definitions": {
                "CommonResult": {
                    "type": "object",
                    "required": ["response_kind"],
                    "properties": {"response_kind": {"type": "string"}}
                }
            }
        });
        let rendered = render_schema_tables(
            &schema,
            Language::English,
            TableRole::Success,
            "api.method.alpha.response",
            RESULT_SHAPE,
        )
        .expect("flattened result");

        assert!(rendered.contains("`method_value`"));
        assert!(rendered.contains("`response_kind`"));
    }

    #[test]
    fn shared_and_method_specific_rejections_remain_distinct() {
        let (base, rejection, dry_run) = common_schemas();
        let result = json!({
            "title": "AlphaResult",
            "type": "object",
            "required": ["base", "value"],
            "properties": {
                "base": {"type": "object"},
                "value": {"type": "string"}
            }
        });
        let shared_descriptor =
            response_descriptor(result.clone(), rejection.clone(), dry_run.clone());
        let shared = CommonResponseSchemas {
            result_base: &base,
            rejected_base: &base,
            dry_run_base: &base,
            rejection: &rejection,
            dry_run: &dry_run,
        };
        let mut descriptors = BTreeMap::new();
        descriptors.insert(shared_descriptor.id().to_owned(), shared_descriptor);
        let response_binding = binding(
            "api.method.alpha.response",
            DocumentContractRole::MethodResponse,
        );
        let rendered = render_response_region(
            std::slice::from_ref(&response_binding),
            &descriptors,
            &shared,
            Language::English,
        )
        .expect("shared rejection");
        assert!(rendered.contents.contains("exact `anyOf` branch union"));
        assert!(rendered.contents.contains("schema-core.md#common-response"));
        assert!(!rendered.contents.contains("| `errors` |"));

        let specific_rejection = json!({
            "title": "AlphaRejectedResponse",
            "type": "object",
            "required": ["base", "errors", "reason"],
            "properties": {
                "base": {"type": "object"},
                "errors": {"type": "array", "items": {"type": "string"}},
                "reason": {"type": "string"}
            }
        });
        let specific_descriptor = response_descriptor(result, specific_rejection, dry_run.clone());
        descriptors.insert(specific_descriptor.id().to_owned(), specific_descriptor);
        let rendered = render_response_region(
            &[response_binding],
            &descriptors,
            &shared,
            Language::English,
        )
        .expect("specific rejection");
        assert!(rendered
            .contents
            .contains("`AlphaRejectedResponse` rejection fields"));
        assert!(rendered.contents.contains("| `reason` |"));
    }

    #[test]
    fn request_and_response_regions_use_distinct_contract_shapes() {
        let request_schema = json!({
            "title": "AlphaRequest",
            "type": "object",
            "required": ["request_value"],
            "properties": {"request_value": {"type": "string"}}
        });
        let result_schema = json!({
            "title": "AlphaResult",
            "type": "object",
            "required": ["response_value"],
            "properties": {"response_value": {"type": "integer"}}
        });
        let (base, rejection, dry_run) = common_schemas();
        let request = descriptor(
            "api.method.alpha.request",
            JsonExampleShape::MethodParams,
            request_schema,
        );
        let response = response_descriptor(result_schema, rejection.clone(), dry_run.clone());
        let mut descriptors = BTreeMap::new();
        descriptors.insert(request.id().to_owned(), request);
        descriptors.insert(response.id().to_owned(), response);
        let request = render_request_region(
            &[binding(
                "api.method.alpha.request",
                DocumentContractRole::MethodRequest,
            )],
            &descriptors,
            Language::English,
        )
        .expect("request region");
        let response = render_response_region(
            &[binding(
                "api.method.alpha.response",
                DocumentContractRole::MethodResponse,
            )],
            &descriptors,
            &CommonResponseSchemas {
                result_base: &base,
                rejected_base: &base,
                dry_run_base: &base,
                rejection: &rejection,
                dry_run: &dry_run,
            },
            Language::English,
        )
        .expect("response region");

        assert!(request.contents.contains("`request_value`"));
        assert!(!request.contents.contains("`response_value`"));
        assert!(response.contents.contains("`response_value`"));
        assert!(!response.contents.contains("`request_value`"));
    }

    #[test]
    fn generator_consumes_all_and_only_resolved_method_bindings_without_route_inference() {
        let descriptors = descriptor_catalog();
        let common = common_response_schemas(&descriptors).expect("common response schemas");
        let method_owner = paired_document(
            "reference.api.method-route-that-names-no-contract",
            "reference/api/method-combined.md",
            [
                binding(
                    "api.method.status.response",
                    DocumentContractRole::MethodResponse,
                ),
                binding(
                    "api.method.intake.request",
                    DocumentContractRole::MethodRequest,
                ),
                binding(
                    "api.method.status.request",
                    DocumentContractRole::MethodRequest,
                ),
                binding(
                    "api.method.intake.response",
                    DocumentContractRole::MethodResponse,
                ),
            ],
        );
        let core_owner = paired_document(
            CORE_SCHEMA_DOC_ID,
            "reference/api/schema-core.md",
            [binding(
                CORE_SCHEMA_CONTRACT_ID,
                DocumentContractRole::SchemaObject,
            )],
        );
        let index = DocIndex {
            indexed_paths: BTreeSet::new(),
            paired_paths: BTreeMap::new(),
            path_doc_ids: BTreeMap::new(),
            paired_documents: BTreeMap::from([
                (method_owner.doc_id.clone(), method_owner),
                (core_owner.doc_id.clone(), core_owner),
            ]),
        };

        let documents =
            contract_documents(&index, &descriptors, &common).expect("resolved contract documents");
        let (_, _, english_regions) = documents
            .iter()
            .find(|(path, _, _)| path == "docs/en/reference/api/method-combined.md")
            .expect("renamed method owner");
        let (_, _, korean_regions) = documents
            .iter()
            .find(|(path, _, _)| path == "docs/ko/reference/api/method-combined.md")
            .expect("paired Korean method owner");

        assert_eq!(english_regions.len(), 2);
        assert_eq!(
            english_regions[0].id,
            "contract-structures api.method.intake.request[params] api.method.status.request[params]"
        );
        assert_eq!(
            english_regions[1].id,
            "contract-structures api.method.intake.response[response_variants] api.method.intake.response[result_body] api.method.intake.response[rejection] api.method.intake.response[dry_run] api.method.status.response[response_variants] api.method.status.response[result_body] api.method.status.response[rejection]"
        );
        assert_eq!(
            english_regions
                .iter()
                .map(|region| region.id.as_str())
                .collect::<Vec<_>>(),
            korean_regions
                .iter()
                .map(|region| region.id.as_str())
                .collect::<Vec<_>>()
        );
    }

    #[test]
    fn tagged_variants_and_closed_values_are_explicit() {
        let schema = json!({
            "title": "TaggedResult",
            "oneOf": [
                {
                    "title": "Ready",
                    "type": "object",
                    "required": ["kind", "items"],
                    "properties": {
                        "kind": {"const": "ready"},
                        "items": {"type": "array", "items": {"$ref": "#/definitions/Item"}}
                    }
                },
                {
                    "title": "Blocked",
                    "type": "object",
                    "required": ["kind", "reason"],
                    "properties": {
                        "kind": {"type": "string", "enum": ["blocked"]},
                        "reason": {"type": ["string", "null"]}
                    }
                }
            ],
            "definitions": {
                "Item": {"type": "object", "properties": {"name": {"type": "string"}}}
            }
        });
        let rendered = render_schema_tables(
            &schema,
            Language::English,
            TableRole::Success,
            "api.method.alpha.response",
            RESULT_SHAPE,
        )
        .expect("tagged variants");

        assert!(rendered.contains("`TaggedResult: Ready`"));
        assert!(rendered.contains("`const(\"ready\")`"));
        assert!(rendered.contains("`Item[]`"));
        assert!(rendered.contains("`string enum(\"blocked\")`"));
    }

    #[test]
    fn unsupported_schema_structure_reports_the_owner() {
        let schema = json!({"title": "Unsupported", "type": "string"});
        let error = render_schema_tables(
            &schema,
            Language::English,
            TableRole::Success,
            "api.method.alpha.response",
            RESULT_SHAPE,
        )
        .expect_err("non-object result must fail");

        assert!(error
            .to_string()
            .contains("unsupported generated structure"));
    }

    #[test]
    fn english_and_korean_rendering_are_deterministic() {
        let schema = json!({
            "title": "AlphaResult",
            "type": "object",
            "required": ["value"],
            "properties": {"value": {"type": ["string", "null"]}}
        });
        let english = render_schema_tables(
            &schema,
            Language::English,
            TableRole::Success,
            "api.method.alpha.response",
            RESULT_SHAPE,
        )
        .expect("English");
        let korean = render_schema_tables(
            &schema,
            Language::Korean,
            TableRole::Success,
            "api.method.alpha.response",
            RESULT_SHAPE,
        )
        .expect("Korean");

        assert_eq!(
            english,
            render_schema_tables(
                &schema,
                Language::English,
                TableRole::Success,
                "api.method.alpha.response",
                RESULT_SHAPE,
            )
            .expect("deterministic English")
        );
        assert!(english.contains("| `value` | yes | yes | `string` |"));
        assert!(korean.contains("| `value` | 예 | 예 | `string` |"));
    }

    #[test]
    fn missing_or_wrong_contract_region_is_rejected() {
        let region = render_region(
            "contract-structures api.method.alpha.response[result_body]".to_owned(),
            "body".to_owned(),
        );
        let missing = "# Method\n";
        assert!(validate_region_inventory(missing, &[region]).is_err());

        let wrong = render_region(
            "contract-structures api.method.beta.response[result_body]".to_owned(),
            "body".to_owned(),
        );
        let expected = render_region(
            "contract-structures api.method.alpha.response[result_body]".to_owned(),
            "body".to_owned(),
        );
        assert!(validate_region_inventory(&wrong.contents, &[expected]).is_err());
    }
}
